/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.UserDAO;
import javax.swing.JOptionPane;
import pojo.user;

/**
 *
 * @author HP
 */
public class changePass extends javax.swing.JFrame {

    /**
     * Creates new form changePass
     */
    public changePass() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lable1 = new javax.swing.JLabel();
        lableOldPass = new javax.swing.JLabel();
        lableNewPass = new javax.swing.JLabel();
        lableNewPass_1 = new javax.swing.JLabel();
        btnChange = new javax.swing.JButton();
        jpOldPass = new javax.swing.JPasswordField();
        jpNewPass = new javax.swing.JPasswordField();
        jpNewPass_1 = new javax.swing.JPasswordField();
        lableExit = new javax.swing.JLabel();

        setBackground(new java.awt.Color(229, 231, 233));
        setUndecorated(true);

        lable1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lable1.setForeground(new java.awt.Color(255, 0, 102));
        lable1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable1.setText("ĐỔI MẬT KHẨU");

        lableOldPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableOldPass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableOldPass.setText("Nhập mật khẩu cũ");

        lableNewPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableNewPass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableNewPass.setText("Nhập mật khẩu mới");

        lableNewPass_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableNewPass_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableNewPass_1.setText("Xác nhận mật khẩu");

        btnChange.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnChange.setText("Thay đổi");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        jpOldPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jpOldPass.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jpNewPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jpNewPass.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jpNewPass_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jpNewPass_1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lableExit.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lableExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_35px.png"))); // NOI18N
        lableExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lableNewPass)
                    .addComponent(lableOldPass)
                    .addComponent(lableNewPass_1))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpNewPass_1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(jpNewPass)
                    .addComponent(jpOldPass))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 237, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lable1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))
                    .addComponent(lableExit, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lableExit)
                .addGap(19, 19, 19)
                .addComponent(lable1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableOldPass)
                    .addComponent(jpOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableNewPass))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableNewPass_1)
                    .addComponent(jpNewPass_1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        String oldPass = jpOldPass.getText();
        String newPass = jpNewPass.getText();
        String newPass_1 = jpNewPass_1.getText();
        user temp = UserDAO.layThongTinUser(login.staticUsername);

        if (!newPass.equals(newPass_1)) {
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu không khớp");
        } else if (!temp.getPassword().equals(oldPass)) {
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu không chính xác");
        } else {
            temp.setPassword(newPass_1);
            //user u = new user(login.staticUsername, newPass, 1, null);
            if (UserDAO.capNhatThongTinUser(temp)) {
                JOptionPane.showMessageDialog(rootPane, "Đổi mật khẩu thành công");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Đổi mật khẩu thất bại");
            }
        }
        this.dispose();
    }//GEN-LAST:event_btnChangeActionPerformed

    private void lableExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableExitMouseClicked
        new updateInfor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lableExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changePass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JPasswordField jpNewPass;
    private javax.swing.JPasswordField jpNewPass_1;
    private javax.swing.JPasswordField jpOldPass;
    private javax.swing.JLabel lable1;
    private javax.swing.JLabel lableExit;
    private javax.swing.JLabel lableNewPass;
    private javax.swing.JLabel lableNewPass_1;
    private javax.swing.JLabel lableOldPass;
    // End of variables declaration//GEN-END:variables
}
