/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.semesterDAO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.semester;

/**
 *
 * @author HP
 */
public class QLHocKi extends javax.swing.JFrame {

    /**
     * Creates new form semester
     */
    DefaultTableModel modelTab1;
    DefaultTableModel modelTab4;

    public QLHocKi() {
        initComponents();
        setLocationRelativeTo(null);
        modelTab1 = (DefaultTableModel) tableTab1.getModel();
        modelTab4 = (DefaultTableModel) tableTab4.getModel();

        jp1.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
    }

    public void showTableTab1() {
        modelTab1.setNumRows(0);
        List<semester> listSemester = semesterDAO.layDanhSachSemester();
        for (semester t : listSemester) {
            boolean flag;
            int check = t.getHocKyHienTai();
            modelTab1.addRow(new Object[]{
                t.getName(), t.getYear(), t.getNgayBatDau(), t.getNgayKetThuc(), check == 0 ? false : true
            });
        }
    }

    public void showTableTab4() {
        modelTab4.setNumRows(0);
        List<semester> listSemester = semesterDAO.layDanhSachSemester();
        for (semester t : listSemester) {
            modelTab4.addRow(new Object[]{
                false, t.getName(), t.getYear(), t.getNgayBatDau(), t.getNgayKetThuc()
            });
        }
    }

    public void showComboboxYearTab3() {
        cbYearTab3.removeAllItems();
        List<semester> listSemester = semesterDAO.layDanhSachSemester();
        List<String> list = new ArrayList<>();
        for (semester s : listSemester){
            list.add(s.getYear());
        }
        
        for (int i = 0; i < list.size() - 1; i ++){
            for (int j = i + 1; j < list.size(); j++){
                if (list.get(i).equals(list.get(j))){
                    list.remove(j);
                    j--;
                }
            }
        }
        
        for (String s : list) {
            cbYearTab3.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        lable = new javax.swing.JLabel();
        tab5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jp4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTab4 = new javax.swing.JTable();
        btnTab4 = new javax.swing.JButton();
        jp3 = new javax.swing.JPanel();
        lableTab3 = new javax.swing.JLabel();
        lableNameTab3 = new javax.swing.JLabel();
        lableYearTab3 = new javax.swing.JLabel();
        btnXoaTab3 = new javax.swing.JButton();
        cbYearTab3 = new javax.swing.JComboBox<>();
        cbNameTab3 = new javax.swing.JComboBox<>();
        jp2 = new javax.swing.JPanel();
        lableTab2 = new javax.swing.JLabel();
        lableNameTab2 = new javax.swing.JLabel();
        lableNgaybdTab2 = new javax.swing.JLabel();
        lableNgayktTab2 = new javax.swing.JLabel();
        btnThemTab2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cb3Tab2 = new javax.swing.JComboBox<>();
        cb2Tab2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cb5Tab2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cb6Tab2 = new javax.swing.JComboBox<>();
        cbHocKiTab2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbYearTab2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cb1Tab2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cb4Tab2 = new javax.swing.JComboBox<>();
        jp1 = new javax.swing.JPanel();
        lableTab1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTab1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý học kì");

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        tab1.setBackground(new java.awt.Color(153, 255, 153));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Xem danh sách");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab2.setBackground(new java.awt.Color(153, 255, 153));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Thêm học kỳ");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab3.setBackground(new java.awt.Color(153, 255, 153));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Xóa học kỳ");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab4.setBackground(new java.awt.Color(153, 255, 153));
        tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab4MouseClicked(evt);
            }
        });

        lable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lable.setText("Set học kỳ hiện tại");

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lable, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        tab4Layout.setVerticalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lable, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab5.setBackground(new java.awt.Color(153, 255, 153));
        tab5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab5MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Quay lại");

        javax.swing.GroupLayout tab5Layout = new javax.swing.GroupLayout(tab5);
        tab5.setLayout(tab5Layout);
        tab5Layout.setHorizontalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab5Layout.setVerticalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp4.setBackground(new java.awt.Color(255, 204, 255));

        tableTab4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableTab4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Select", "Tên học kỳ", "Năm học", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableTab4);
        if (tableTab4.getColumnModel().getColumnCount() > 0) {
            tableTab4.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        btnTab4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTab4.setText("Set");
        btnTab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTab4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp4Layout = new javax.swing.GroupLayout(jp4);
        jp4.setLayout(jp4Layout);
        jp4Layout.setHorizontalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(btnTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jp4Layout.setVerticalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jp3.setBackground(new java.awt.Color(204, 255, 204));

        lableTab3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lableTab3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab3.setText("Xóa học kỳ");

        lableNameTab3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableNameTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableNameTab3.setText("Chọn năm học");

        lableYearTab3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableYearTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableYearTab3.setText("Chọn tên học kì");

        btnXoaTab3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXoaTab3.setText("Xóa");
        btnXoaTab3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTab3ActionPerformed(evt);
            }
        });

        cbYearTab3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbYearTab3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbYearTab3ActionPerformed(evt);
            }
        });

        cbNameTab3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jp3Layout = new javax.swing.GroupLayout(jp3);
        jp3.setLayout(jp3Layout);
        jp3Layout.setHorizontalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(lableTab3))
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableNameTab3)
                            .addComponent(lableYearTab3))
                        .addGap(67, 67, 67)
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbYearTab3, 0, 256, Short.MAX_VALUE)
                            .addComponent(cbNameTab3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(btnXoaTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jp3Layout.setVerticalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lableTab3)
                .addGap(68, 68, 68)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableNameTab3)
                    .addComponent(cbYearTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableYearTab3)
                    .addComponent(cbNameTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(btnXoaTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jp2.setBackground(new java.awt.Color(255, 204, 255));

        lableTab2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lableTab2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab2.setText("Thêm học kỳ");

        lableNameTab2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableNameTab2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableNameTab2.setText("Chọn học kỳ");

        lableNgaybdTab2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableNgaybdTab2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableNgaybdTab2.setText("Chọn ngày bắt đầu");

        lableNgayktTab2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableNgayktTab2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableNgayktTab2.setText("Chọn ngày kết thúc");

        btnThemTab2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThemTab2.setText("Thêm");
        btnThemTab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTab2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Tháng");

        cb3Tab2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cb2Tab2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb2Tab2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cb2Tab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2Tab2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Ngày");

        cb5Tab2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb5Tab2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cb5Tab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb5Tab2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Ngày");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Tháng");

        cb6Tab2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cbHocKiTab2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbHocKiTab2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HK1", "HK2", "HK3" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Chọn năm học");

        cbYearTab2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbYearTab2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Năm");

        cb1Tab2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb1Tab2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Năm");

        cb4Tab2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb4Tab2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addComponent(lableNameTab2)
                                .addGap(91, 91, 91)
                                .addComponent(cbHocKiTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(cbYearTab2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lableNgayktTab2)
                            .addComponent(lableNgaybdTab2)))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addContainerGap(166, Short.MAX_VALUE)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(cb4Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cb1Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThemTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb2Tab2, 0, 71, Short.MAX_VALUE)
                                    .addComponent(cb5Tab2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(14, 14, 14)
                                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(cb6Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jp2Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(cb3Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(lableTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lableTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbHocKiTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableNameTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(btnThemTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbYearTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(lableNgaybdTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cb2Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cb3Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb1Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(16, 16, 16)
                        .addComponent(lableNgayktTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cb5Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(cb6Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb4Tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jp1.setBackground(new java.awt.Color(204, 204, 255));

        lableTab1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lableTab1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab1.setText("Danh sách học kỳ");

        tableTab1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableTab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên học kỳ", "Năm học", "Ngày bắt đầu", "Ngày kết thúc", "Học kỳ hiện tại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTab1);

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(lableTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lableTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        jp1.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);

        tab1.setBackground(new Color(204, 204, 255));

        tab2.setBackground(new Color(153, 255, 153));
        tab3.setBackground(new Color(153, 255, 153));
        tab4.setBackground(new Color(153, 255, 153));
        tab5.setBackground(new Color(153, 255, 153));

        showTableTab1();
    }//GEN-LAST:event_tab1MouseClicked

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        jp1.setVisible(false);
        jp2.setVisible(true);
        jp3.setVisible(false);
        jp4.setVisible(false);

        tab2.setBackground(new Color(204, 204, 255));

        tab1.setBackground(new Color(153, 255, 153));
        tab3.setBackground(new Color(153, 255, 153));
        tab4.setBackground(new Color(153, 255, 153));
        tab5.setBackground(new Color(153, 255, 153));
    }//GEN-LAST:event_tab2MouseClicked

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(true);
        jp4.setVisible(false);

        tab3.setBackground(new Color(204, 204, 255));

        tab2.setBackground(new Color(153, 255, 153));
        tab1.setBackground(new Color(153, 255, 153));
        tab4.setBackground(new Color(153, 255, 153));
        showComboboxYearTab3();
        tab5.setBackground(new Color(153, 255, 153));    }//GEN-LAST:event_tab3MouseClicked

    private void tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab4MouseClicked
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(true);

        tab4.setBackground(new Color(204, 204, 255));

        tab2.setBackground(new Color(153, 255, 153));
        tab3.setBackground(new Color(153, 255, 153));
        tab1.setBackground(new Color(153, 255, 153));
        tab5.setBackground(new Color(153, 255, 153));

        showTableTab4();
    }//GEN-LAST:event_tab4MouseClicked

    private void tab5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab5MouseClicked
        new GiaoVuGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tab5MouseClicked

    private boolean checkNgayLonHon(String[] s1, String[] s2) {
        for (int i = 2; i >= 0; i--) {
            if ((s1[i]).compareTo(s2[i]) < 0) {
                return false;
            } else if ((s1[i]).compareTo(s2[i]) > 0) {
                return true;
            }
        }
        return true;
    }

    private void btnThemTab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTab2ActionPerformed
        String name = cbHocKiTab2.getSelectedItem().toString();
        String year = cbYearTab2.getSelectedItem().toString();

        if (cb3Tab2.getSelectedItem() == null || cb6Tab2.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(rootPane, "Ngày không được rỗng!");
            return;
        }

        List<semester> listSemester = semesterDAO.layDanhSachSemester();
        for (semester s : listSemester) {
            if (name.equals(s.getName()) && year.equals(s.getYear())) {
                JOptionPane.showMessageDialog(rootPane, "Học kỳ đã tồn tại!");
                return;
            }
        }

        String[] NgayBatDau = {cb3Tab2.getSelectedItem().toString(), cb2Tab2.getSelectedItem().toString(),
            cb1Tab2.getSelectedItem().toString()};
        String[] NgayKetThuc = {cb6Tab2.getSelectedItem().toString(), cb5Tab2.getSelectedItem().toString(),
            cb4Tab2.getSelectedItem().toString()};

        if (checkNgayLonHon(NgayBatDau, NgayKetThuc) == true) {
            JOptionPane.showMessageDialog(rootPane, "Ngày kết thúc học kì phải sau ngày bắt đầu học kì!");
            return;
        }

        String ngayBatDau = cb3Tab2.getSelectedItem().toString() + "-" + cb2Tab2.getSelectedItem().toString()
                + "-" + cb1Tab2.getSelectedItem().toString();
        String ngayKetThuc = cb6Tab2.getSelectedItem().toString() + "-" + cb5Tab2.getSelectedItem().toString()
                + "-" + cb4Tab2.getSelectedItem().toString();
        semester u = new semester(ngayBatDau, year, name, ngayKetThuc, 0);
        if (semesterDAO.addSemester(u) == true) {
            JOptionPane.showMessageDialog(rootPane, "Thêm học kỳ thành công!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Thời gian bắt đầu học kỳ đã tồn tại!");
        }
    }//GEN-LAST:event_btnThemTab2ActionPerformed

    private void btnXoaTab3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTab3ActionPerformed
        String name = cbNameTab3.getSelectedItem().toString();
        String year = cbYearTab3.getSelectedItem().toString();

        if (semesterDAO.xoaSemeter(name, year) == true) {
            JOptionPane.showMessageDialog(rootPane, "Xóa học kỳ thành công!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Xóa học kì thất bại!");
        }
    }//GEN-LAST:event_btnXoaTab3ActionPerformed

    private void btnTab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTab4ActionPerformed
        int count = 0;

        for (int i = 0; i < modelTab4.getRowCount(); i++) {
            if ((boolean) modelTab4.getValueAt(i, 0) == true) {
                count++;
            }
        }

        if (count == 0) {
            JOptionPane.showMessageDialog(rootPane, "Chưa set học kỳ nào làm học kỳ hiện tại!");
            return;
        } else if (count > 1) {
            JOptionPane.showMessageDialog(rootPane, "Chỉ được set 1 học kỳ làm học kỳ hiện tại!");
            return;
        }

        for (int i = 0; i < modelTab4.getRowCount(); i++) {
            if ((boolean) modelTab4.getValueAt(i, 0) == true) {
                String name = (String) modelTab4.getValueAt(i, 1);
                String year = (String) modelTab4.getValueAt(i, 2);
                semester s = semesterDAO.layHocKyVaNamCuaSemester(name, year);
                s.setHocKyHienTai(1);
                if (semesterDAO.capNhatThongTinSemester(s) == true) {
                    JOptionPane.showMessageDialog(rootPane, "Set học kỳ thành công!");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Set học kỳ thất bại!");
                }
            } else {
                String name = (String) modelTab4.getValueAt(i, 1);
                String year = (String) modelTab4.getValueAt(i, 2);
                semester s = semesterDAO.layHocKyVaNamCuaSemester(name, year);
                s.setHocKyHienTai(0);
                if (semesterDAO.capNhatThongTinSemester(s) == true) {
                    System.out.println("Set học kỳ hiện tại thành học kỳ không hiện tại!");
                }
            }
        }
    }//GEN-LAST:event_btnTab4ActionPerformed

    private void cb2Tab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2Tab2ActionPerformed
        String s1 = cb2Tab2.getSelectedItem().toString();
        if (s1.equals("02")) {
            for (int i = 1; i <= 29; i++) {
                if (i > 9) {
                    cb3Tab2.addItem(Integer.toString(i));
                } else {
                    cb3Tab2.addItem("0" + Integer.toString(i));
                }
            }
        } else if (s1.equals("04") || s1.equals("06") || s1.equals("09") || s1.equals("11")) {
            for (int i = 1; i <= 30; i++) {
                if (i > 9) {
                    cb3Tab2.addItem(Integer.toString(i));
                } else {
                    cb3Tab2.addItem("0" + Integer.toString(i));
                }
            }
        } else {
            for (int i = 1; i <= 31; i++) {
                if (i > 9) {
                    cb3Tab2.addItem(Integer.toString(i));
                } else {
                    cb3Tab2.addItem("0" + Integer.toString(i));
                }
            }
        }
    }//GEN-LAST:event_cb2Tab2ActionPerformed

    private void cb5Tab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb5Tab2ActionPerformed
        String s1 = cb5Tab2.getSelectedItem().toString();
        if (s1.equals("02")) {
            for (int i = 1; i <= 29; i++) {
                if (i > 9) {
                    cb6Tab2.addItem(Integer.toString(i));
                } else {
                    cb6Tab2.addItem("0" + Integer.toString(i));
                }
            }
        } else if (s1.equals("04") || s1.equals("06") || s1.equals("09") || s1.equals("11")) {
            for (int i = 1; i <= 30; i++) {
                if (i > 9) {
                    cb6Tab2.addItem(Integer.toString(i));
                } else {
                    cb6Tab2.addItem("0" + Integer.toString(i));
                }
            }
        } else {
            for (int i = 1; i <= 31; i++) {
                if (i > 9) {
                    cb6Tab2.addItem(Integer.toString(i));
                } else {
                    cb6Tab2.addItem("0" + Integer.toString(i));
                }
            }
        }
    }//GEN-LAST:event_cb5Tab2ActionPerformed

    private void cbYearTab3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbYearTab3ActionPerformed
        if (cbYearTab3.getSelectedItem() == null){
            //System.out.println("Rong roi!");
            return;
        }
        String year = cbYearTab3.getSelectedItem().toString();
        
        List<semester> list = semesterDAO.layDanhSachSemester();
        cbNameTab3.removeAllItems();
        for (semester s : list) {
            if (s.getYear().equals(year)) {
                cbNameTab3.addItem(s.getName());
            }
        }
    }//GEN-LAST:event_cbYearTab3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLHocKi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLHocKi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLHocKi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLHocKi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLHocKi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTab4;
    private javax.swing.JButton btnThemTab2;
    private javax.swing.JButton btnXoaTab3;
    private javax.swing.JComboBox<String> cb1Tab2;
    private javax.swing.JComboBox<String> cb2Tab2;
    private javax.swing.JComboBox<String> cb3Tab2;
    private javax.swing.JComboBox<String> cb4Tab2;
    private javax.swing.JComboBox<String> cb5Tab2;
    private javax.swing.JComboBox<String> cb6Tab2;
    private javax.swing.JComboBox<String> cbHocKiTab2;
    private javax.swing.JComboBox<String> cbNameTab3;
    private javax.swing.JComboBox<String> cbYearTab2;
    private javax.swing.JComboBox<String> cbYearTab3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    private javax.swing.JLabel lable;
    private javax.swing.JLabel lableNameTab2;
    private javax.swing.JLabel lableNameTab3;
    private javax.swing.JLabel lableNgaybdTab2;
    private javax.swing.JLabel lableNgayktTab2;
    private javax.swing.JLabel lableTab1;
    private javax.swing.JLabel lableTab2;
    private javax.swing.JLabel lableTab3;
    private javax.swing.JLabel lableYearTab3;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tab5;
    private javax.swing.JTable tableTab1;
    private javax.swing.JTable tableTab4;
    // End of variables declaration//GEN-END:variables
}
