/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.SubjectDAO;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.subject;

/**
 *
 * @author HP
 */
public class QLMonHoc extends javax.swing.JFrame {

    /**
     * Creates new form QLMonHoc
     */
    DefaultTableModel modelTab1;
    DefaultTableModel modelTab2;

    public QLMonHoc() {
        initComponents();
        setLocationRelativeTo(null);
        modelTab1 = (DefaultTableModel) tableTab1.getModel();
        modelTab2 = (DefaultTableModel) tableTab2.getModel();

        jp1.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
    }

    public void showTableTab1() {
        modelTab1.setNumRows(0);
        List<subject> listSubject = SubjectDAO.layDanhSachSubject();
        for (subject s : listSubject) {
            modelTab1.addRow(new Object[]{
                s.getMaMonHoc(), s.getName(), s.getSoTinChi()
            });
        }
    }

    public void showComboboxTab2() {
        cbTab2.removeAllItems();
        List<subject> list = SubjectDAO.layDanhSachSubject();
        for (subject s : list) {
            cbTab2.addItem(s.getMaMonHoc());
        }
    }

    public void showComboboxTab4() {
        cbTab4.removeAllItems();
        List<subject> list = SubjectDAO.layDanhSachSubject();
        for (subject s : list) {
            cbTab4.addItem(s.getMaMonHoc());
        }
    }

    public void showComboboxTab5() {
        cbTab5.removeAllItems();
        List<subject> list = SubjectDAO.layDanhSachSubject();
        for (subject s : list) {
            cbTab5.addItem(s.getMaMonHoc());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tab2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tab1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tab6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jpLogout = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jp2 = new javax.swing.JPanel();
        lableMMHTab2 = new javax.swing.JLabel();
        lableTab2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTab2 = new javax.swing.JTable();
        cbTab2 = new javax.swing.JComboBox<>();
        lableExitTab2 = new javax.swing.JLabel();
        jp4 = new javax.swing.JPanel();
        lableTab4 = new javax.swing.JLabel();
        lableMMHTab4 = new javax.swing.JLabel();
        lableNameTab4 = new javax.swing.JLabel();
        lableSTCTab4 = new javax.swing.JLabel();
        tfNameTab4 = new javax.swing.JTextField();
        tfSTCTab4 = new javax.swing.JTextField();
        btnUpdateTab4 = new javax.swing.JButton();
        cbTab4 = new javax.swing.JComboBox<>();
        lableExitTab4 = new javax.swing.JLabel();
        jp5 = new javax.swing.JPanel();
        lableTab5 = new javax.swing.JLabel();
        lableMMHTab5 = new javax.swing.JLabel();
        btnTab5 = new javax.swing.JButton();
        cbTab5 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tfTab5 = new javax.swing.JTextField();
        lableExitTab5 = new javax.swing.JLabel();
        jp3 = new javax.swing.JPanel();
        lableTab3 = new javax.swing.JLabel();
        lableMMHTab3 = new javax.swing.JLabel();
        lableNameTab3 = new javax.swing.JLabel();
        lableSTCTab3 = new javax.swing.JLabel();
        tfMMHTab3 = new javax.swing.JTextField();
        tfNameTab3 = new javax.swing.JTextField();
        tfSTCTab3 = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        lableExitTab3 = new javax.swing.JLabel();
        jp1 = new javax.swing.JPanel();
        lableExitTab1 = new javax.swing.JLabel();
        lableTab1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTab1 = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý môn học");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(159, 226, 191));

        tab2.setBackground(new java.awt.Color(253, 254, 254));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Tìm kiếm môn học");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab3.setBackground(new java.awt.Color(253, 254, 254));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Thêm môn học");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab1.setBackground(new java.awt.Color(253, 254, 254));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Xem danh sách");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab5.setBackground(new java.awt.Color(253, 254, 254));
        tab5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab5MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Xóa môn học");

        javax.swing.GroupLayout tab5Layout = new javax.swing.GroupLayout(tab5);
        tab5.setLayout(tab5Layout);
        tab5Layout.setHorizontalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab5Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab5Layout.setVerticalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab6.setBackground(new java.awt.Color(253, 254, 254));
        tab6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab6MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Quay lại");

        javax.swing.GroupLayout tab6Layout = new javax.swing.GroupLayout(tab6);
        tab6.setLayout(tab6Layout);
        tab6Layout.setHorizontalGroup(
            tab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab6Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab6Layout.setVerticalGroup(
            tab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab4.setBackground(new java.awt.Color(253, 254, 254));
        tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab4MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Cập nhật thông tin");

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab4Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(45, 45, 45))
        );
        tab4Layout.setVerticalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_teacher_50px.png"))); // NOI18N

        jpLogout.setBackground(new java.awt.Color(255, 102, 102));
        jpLogout.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jpLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_shutdown_25px_1.png"))); // NOI18N
        jpLogout.setText("Đăng xuất");
        jpLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpLogoutMouseClicked(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addComponent(jLabel8))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(jpLogout))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jpLogout)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jp2.setBackground(new java.awt.Color(242, 243, 244));

        lableMMHTab2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableMMHTab2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableMMHTab2.setText("Chọn mã môn học");

        lableTab2.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lableTab2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab2.setText("Tìm kiếm môn học");

        tableTab2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableTab2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã môn học", "Tên môn học", "Số tín chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableTab2);

        cbTab2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbTab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTab2ActionPerformed(evt);
            }
        });

        lableExitTab2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lableExitTab2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_35px.png"))); // NOI18N
        lableExitTab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableExitTab2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(lableTab2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lableExitTab2))
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addComponent(lableMMHTab2)
                        .addGap(55, 55, 55)
                        .addComponent(cbTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 91, Short.MAX_VALUE))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lableTab2))
                    .addComponent(lableExitTab2))
                .addGap(36, 36, 36)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableMMHTab2)
                    .addComponent(cbTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jp4.setBackground(new java.awt.Color(242, 243, 244));

        lableTab4.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lableTab4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab4.setText("Cập nhật thông tin");

        lableMMHTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableMMHTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableMMHTab4.setText("Chọn mã môn học");

        lableNameTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableNameTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableNameTab4.setText("Nhập tên môn học mới");

        lableSTCTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableSTCTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableSTCTab4.setText("Nhập số tín chỉ mới");

        tfNameTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNameTab4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tfSTCTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfSTCTab4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnUpdateTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdateTab4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_update_user_25px_2.png"))); // NOI18N
        btnUpdateTab4.setText("Update");
        btnUpdateTab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTab4ActionPerformed(evt);
            }
        });

        cbTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lableExitTab4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lableExitTab4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_35px.png"))); // NOI18N
        lableExitTab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableExitTab4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp4Layout = new javax.swing.GroupLayout(jp4);
        jp4.setLayout(jp4Layout);
        jp4Layout.setHorizontalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableNameTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lableSTCTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lableMMHTab4))
                        .addGap(20, 20, 20)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfSTCTab4, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(cbTab4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfNameTab4)))
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(lableTab4))
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(btnUpdateTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lableExitTab4))
        );
        jp4Layout.setVerticalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addComponent(lableExitTab4)
                .addGap(3, 3, 3)
                .addComponent(lableTab4)
                .addGap(79, 79, 79)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableMMHTab4))
                .addGap(41, 41, 41)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableNameTab4)
                    .addComponent(tfNameTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableSTCTab4)
                    .addComponent(tfSTCTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(btnUpdateTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jp5.setBackground(new java.awt.Color(242, 243, 244));

        lableTab5.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lableTab5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab5.setText("Xóa môn học");

        lableMMHTab5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableMMHTab5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableMMHTab5.setText("Chọn mã môn học");

        btnTab5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTab5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_25px.png"))); // NOI18N
        btnTab5.setText("Xóa");
        btnTab5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTab5ActionPerformed(evt);
            }
        });

        cbTab5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbTab5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTab5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Tên môn học");

        tfTab5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfTab5.setEnabled(false);

        lableExitTab5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lableExitTab5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_35px.png"))); // NOI18N
        lableExitTab5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableExitTab5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp5Layout = new javax.swing.GroupLayout(jp5);
        jp5.setLayout(jp5Layout);
        jp5Layout.setHorizontalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5Layout.createSequentialGroup()
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(lableTab5))
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableMMHTab5)
                            .addComponent(jLabel7))
                        .addGap(56, 56, 56)
                        .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTab5, 0, 298, Short.MAX_VALUE)
                            .addComponent(tfTab5)))
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(btnTab5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(268, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lableExitTab5))
        );
        jp5Layout.setVerticalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5Layout.createSequentialGroup()
                .addComponent(lableExitTab5)
                .addGap(56, 56, 56)
                .addComponent(lableTab5)
                .addGap(47, 47, 47)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableMMHTab5)
                    .addComponent(cbTab5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel7))
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(tfTab5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addComponent(btnTab5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jp3.setBackground(new java.awt.Color(242, 243, 244));

        lableTab3.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lableTab3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab3.setText("Thêm môn học");

        lableMMHTab3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableMMHTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableMMHTab3.setText("Nhập mã môn học");

        lableNameTab3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableNameTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableNameTab3.setText("Nhập tên môn học");

        lableSTCTab3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableSTCTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableSTCTab3.setText("Nhập số tín chỉ");

        tfMMHTab3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfMMHTab3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tfNameTab3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNameTab3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tfSTCTab3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfSTCTab3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_add_25px.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        lableExitTab3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lableExitTab3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_35px.png"))); // NOI18N
        lableExitTab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableExitTab3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp3Layout = new javax.swing.GroupLayout(jp3);
        jp3.setLayout(jp3Layout);
        jp3Layout.setHorizontalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(lableTab3))
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableNameTab3)
                            .addComponent(lableSTCTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lableMMHTab3))
                        .addGap(31, 31, 31)
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfNameTab3, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                            .addComponent(tfMMHTab3)
                            .addComponent(tfSTCTab3))))
                .addContainerGap(228, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3Layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(362, 362, 362))
                    .addComponent(lableExitTab3, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jp3Layout.setVerticalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addComponent(lableExitTab3)
                .addGap(14, 14, 14)
                .addComponent(lableTab3)
                .addGap(50, 50, 50)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableMMHTab3)
                    .addComponent(tfMMHTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNameTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableNameTab3))
                .addGap(45, 45, 45)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSTCTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableSTCTab3))
                .addGap(75, 75, 75)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jp1.setBackground(new java.awt.Color(242, 243, 244));

        lableExitTab1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lableExitTab1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_35px.png"))); // NOI18N
        lableExitTab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableExitTab1MouseClicked(evt);
            }
        });

        lableTab1.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lableTab1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab1.setText("Danh sách môn học");

        tableTab1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tableTab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã môn học", "Tên môn học", "Số tín chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTab1);

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(lableTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lableExitTab1))
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addComponent(lableExitTab1)
                .addGap(16, 16, 16)
                .addComponent(lableTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        jp1.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
        tab1.setBackground(new Color(204, 204, 255));

        tab2.setBackground(new Color(253, 254, 254));
        tab3.setBackground(new Color(253, 254, 254));
        tab4.setBackground(new Color(253, 254, 254));
        tab5.setBackground(new Color(253, 254, 254));
        tab6.setBackground(new Color(253, 254, 254));

        showTableTab1();
    }//GEN-LAST:event_tab1MouseClicked

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        jp1.setVisible(false);
        jp2.setVisible(true);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
        tab2.setBackground(new Color(204, 204, 255));

        tab1.setBackground(new Color(253, 254, 254));
        tab3.setBackground(new Color(253, 254, 254));
        tab4.setBackground(new Color(253, 254, 254));
        tab5.setBackground(new Color(253, 254, 254));
        tab6.setBackground(new Color(253, 254, 254));

        showComboboxTab2();
    }//GEN-LAST:event_tab2MouseClicked

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(true);
        jp4.setVisible(false);
        jp5.setVisible(false);
        tab3.setBackground(new Color(204, 204, 255));

        tab2.setBackground(new Color(253, 254, 254));
        tab1.setBackground(new Color(253, 254, 254));
        tab4.setBackground(new Color(253, 254, 254));
        tab5.setBackground(new Color(253, 254, 254));
        tab6.setBackground(new Color(253, 254, 254));

        tfNameTab3.setText("");
        tfMMHTab3.setText("");
        tfSTCTab3.setText("");
    }//GEN-LAST:event_tab3MouseClicked

    private void tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab4MouseClicked
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(true);
        jp5.setVisible(false);
        tab4.setBackground(new Color(204, 204, 255));

        tab2.setBackground(new Color(253, 254, 254));
        tab3.setBackground(new Color(253, 254, 254));
        tab1.setBackground(new Color(253, 254, 254));
        tab5.setBackground(new Color(253, 254, 254));
        tab6.setBackground(new Color(253, 254, 254));

        tfNameTab4.setText("");
        tfSTCTab4.setText("");
        showComboboxTab4();
    }//GEN-LAST:event_tab4MouseClicked

    private void tab5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab5MouseClicked
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(true);
        tab5.setBackground(new Color(204, 204, 255));

        tab2.setBackground(new Color(253, 254, 254));
        tab3.setBackground(new Color(253, 254, 254));
        tab4.setBackground(new Color(253, 254, 254));
        tab1.setBackground(new Color(253, 254, 254));
        tab6.setBackground(new Color(253, 254, 254));

        showComboboxTab5();
    }//GEN-LAST:event_tab5MouseClicked

    private void tab6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab6MouseClicked
        new GiaoVuGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tab6MouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String maMonHoc = tfMMHTab3.getText();
        String name = tfNameTab3.getText();
        if (maMonHoc.equals("") || name.equals("") || tfSTCTab3.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Thông tin không được để trống!");
            return;
        }
        int soTinChi = Integer.parseInt(tfSTCTab3.getText());

        if (SubjectDAO.layThongTinSubject(maMonHoc) != null) {
            JOptionPane.showMessageDialog(rootPane, "Mã môn học đã tồn tại!");
        } else {
            subject s = new subject(maMonHoc, name, soTinChi);
            if (SubjectDAO.addSubject(s) == true) {
                JOptionPane.showMessageDialog(rootPane, "Thêm môn học thành công!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thêm môn học thất bại!");
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnUpdateTab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTab4ActionPerformed
        String maMonHoc = cbTab4.getSelectedItem().toString();
        String name = tfNameTab4.getText();
        String soTinChi = tfSTCTab4.getText();
        if (maMonHoc.equals("") || name.equals("") || soTinChi.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Thông tin không được để trống!");
            return;
        }

        subject s = SubjectDAO.layThongTinSubject(maMonHoc);
        s.setName(name);
        s.setSoTinChi(Integer.parseInt(soTinChi));
        if (SubjectDAO.capNhatThongTinSubject(s) == true) {
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin môn học thành công!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin môn học thất bại!");
        }
    }//GEN-LAST:event_btnUpdateTab4ActionPerformed

    private void btnTab5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTab5ActionPerformed
        if (cbTab5.getSelectedItem() == null)
            return;
        String maMonHoc = cbTab5.getSelectedItem().toString();

        if (SubjectDAO.xoaSubject(maMonHoc) == true) {
            JOptionPane.showMessageDialog(rootPane, "Xóa môn học thành công!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Xóa môn học thấy bại!");
        }
    }//GEN-LAST:event_btnTab5ActionPerformed

    private void cbTab5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTab5ActionPerformed
        if (cbTab5.getSelectedItem() == null)
            return;
        
        subject s = SubjectDAO.layThongTinSubject(cbTab5.getSelectedItem().toString());
        tfTab5.setText(s.getName());
    }//GEN-LAST:event_cbTab5ActionPerformed

    private void cbTab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTab2ActionPerformed
        if (cbTab2.getSelectedItem() == null)
            return;
        String maMonHoc = cbTab2.getSelectedItem().toString();
        modelTab2.setNumRows(0);
        subject s = SubjectDAO.layThongTinSubject(maMonHoc);
        modelTab2.addRow(new Object[]{
            s.getMaMonHoc(), s.getName(), s.getSoTinChi()
        });

    }//GEN-LAST:event_cbTab2ActionPerformed

    private void jpLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLogoutMouseClicked
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jpLogoutMouseClicked

    private void lableExitTab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableExitTab1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lableExitTab1MouseClicked

    private void lableExitTab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableExitTab3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lableExitTab3MouseClicked

    private void lableExitTab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableExitTab2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lableExitTab2MouseClicked

    private void lableExitTab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableExitTab4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lableExitTab4MouseClicked

    private void lableExitTab5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableExitTab5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lableExitTab5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLMonHoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTab5;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnUpdateTab4;
    private javax.swing.JComboBox<String> cbTab2;
    private javax.swing.JComboBox<String> cbTab4;
    private javax.swing.JComboBox<String> cbTab5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    private javax.swing.JPanel jp5;
    private javax.swing.JLabel jpLogout;
    private javax.swing.JLabel lableExitTab1;
    private javax.swing.JLabel lableExitTab2;
    private javax.swing.JLabel lableExitTab3;
    private javax.swing.JLabel lableExitTab4;
    private javax.swing.JLabel lableExitTab5;
    private javax.swing.JLabel lableMMHTab2;
    private javax.swing.JLabel lableMMHTab3;
    private javax.swing.JLabel lableMMHTab4;
    private javax.swing.JLabel lableMMHTab5;
    private javax.swing.JLabel lableNameTab3;
    private javax.swing.JLabel lableNameTab4;
    private javax.swing.JLabel lableSTCTab3;
    private javax.swing.JLabel lableSTCTab4;
    private javax.swing.JLabel lableTab1;
    private javax.swing.JLabel lableTab2;
    private javax.swing.JLabel lableTab3;
    private javax.swing.JLabel lableTab4;
    private javax.swing.JLabel lableTab5;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tab5;
    private javax.swing.JPanel tab6;
    private javax.swing.JTable tableTab1;
    private javax.swing.JTable tableTab2;
    private javax.swing.JTextField tfMMHTab3;
    private javax.swing.JTextField tfNameTab3;
    private javax.swing.JTextField tfNameTab4;
    private javax.swing.JTextField tfSTCTab3;
    private javax.swing.JTextField tfSTCTab4;
    private javax.swing.JTextField tfTab5;
    // End of variables declaration//GEN-END:variables
}
