/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ClassDAO;
import dao.StudentDAO;
import dao.SubjectDAO;
import dao.UserDAO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.student;
import pojo.subject;
import pojo.ClassPojo;
import pojo.user;

/**
 *
 * @author HP
 */
public class QLSVTrongLopHoc extends javax.swing.JFrame {

    /**
     * Creates new form QLSVTrongLopHoc
     */
    private DefaultTableModel modelTab1;
    private DefaultTableModel modelTab6;
    private DefaultTableModel modelTab2;

    public QLSVTrongLopHoc() {
        initComponents();
        setLocationRelativeTo(null);
        modelTab1 = (DefaultTableModel) tableTab1.getModel();
        modelTab6 = (DefaultTableModel) tableTab6.getModel();
        modelTab2 = (DefaultTableModel) tableTab2.getModel();

        jp1.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
    }

    public boolean checkMaLop(String a, List<pojo.ClassPojo> cl) {
        for (pojo.ClassPojo c : cl) {
            if (c.getMaLop().equals(a)) {
                return true;
            }
        }
        return false;
    }

    public void showTableTab1(int index) {
        modelTab1.setNumRows(0);
        List<student> listStudent = StudentDAO.layDanhSachStudent();

        if (index == 0) {
            for (student t : listStudent) {
                modelTab1.addRow(new Object[]{
                    t.getId(), t.getName(), t.getGioiTinh() == 1 ? "Nam" : "Nữ", t.getAddress()
                });
            }
        } else {
            for (student t : listStudent) {
                List<pojo.ClassPojo> myList = new ArrayList<>(t.getClass_student());
                if (checkMaLop(comboboxTab1.getItemAt(index), myList) == true) {
                    modelTab1.addRow(new Object[]{
                        t.getId(), t.getName(), t.getGioiTinh() == 1 ? "Nam" : "Nữ", t.getAddress()
                    });
                }
            }
        }
    }

    public void showComboboxTab1() {
        List<ClassPojo> listClass = ClassDAO.layDanhSachClass();
        comboboxTab1.addItem("Tất cả");
        for (pojo.ClassPojo c : listClass) {
            comboboxTab1.addItem(c.getMaLop());
        }
    }

    public void showTableTab6() {
//        modelTab6.setNumRows(0);
//        List<subject> listSubject = SubjectDAO.layDanhSachSubject();
//
//        for (subject sb : listSubject) {
//            if (sb.getStudentsList().size() != 0) {
//                modelTab6.addRow(new Object[]{
//                    sb.getMaMonHoc(), sb.getName(), sb.getSoTinChi(), Boolean.TRUE
//                });
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tab5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tab6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tab7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jp3 = new javax.swing.JPanel();
        lableTab3 = new javax.swing.JLabel();
        lableIDTab3 = new javax.swing.JLabel();
        lableNameTab3 = new javax.swing.JLabel();
        lableAddressTab3 = new javax.swing.JLabel();
        cbGioiTinhTab3 = new javax.swing.JComboBox<>();
        lableGioiTinhTab3 = new javax.swing.JLabel();
        lableClassTab3 = new javax.swing.JLabel();
        btnTab3 = new javax.swing.JButton();
        tfIDTab3 = new javax.swing.JTextField();
        tfNameTab3 = new javax.swing.JTextField();
        tfAddressTab3 = new javax.swing.JTextField();
        cbClassTab3 = new javax.swing.JComboBox<>();
        jp6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTab6 = new javax.swing.JTable();
        lableTab6 = new javax.swing.JLabel();
        jp5 = new javax.swing.JPanel();
        jp4 = new javax.swing.JPanel();
        lableAddressTab4 = new javax.swing.JLabel();
        cbGioiTinhTab4 = new javax.swing.JComboBox<>();
        lableGioiTinhTab4 = new javax.swing.JLabel();
        lableClassTab4 = new javax.swing.JLabel();
        btnTab4 = new javax.swing.JButton();
        tfIDTab4 = new javax.swing.JTextField();
        tfNameTab4 = new javax.swing.JTextField();
        tfAddressTab4 = new javax.swing.JTextField();
        lableTab4 = new javax.swing.JLabel();
        cbClassTab4 = new javax.swing.JComboBox<>();
        lableIDTab4 = new javax.swing.JLabel();
        lableNameTab4 = new javax.swing.JLabel();
        jp2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTab2 = new javax.swing.JTable();
        tfTab2 = new javax.swing.JTextField();
        lableTab2 = new javax.swing.JLabel();
        lableIdTab2 = new javax.swing.JLabel();
        btnTab2 = new javax.swing.JButton();
        jp1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTab1 = new javax.swing.JTable();
        lableTab1 = new javax.swing.JLabel();
        comboboxTab1 = new javax.swing.JComboBox<>();
        lableLuaChonTab1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        tab1.setBackground(new java.awt.Color(204, 255, 204));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Xem danh sách");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab2.setBackground(new java.awt.Color(204, 255, 204));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Tìm kiếm");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab3.setBackground(new java.awt.Color(204, 255, 204));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Thêm sinh viên");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab4.setBackground(new java.awt.Color(204, 255, 204));
        tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab4MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Cập nhật thông tin");

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tab4Layout.setVerticalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab5.setBackground(new java.awt.Color(204, 255, 204));
        tab5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab5MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Reset mật khẩu");

        javax.swing.GroupLayout tab5Layout = new javax.swing.GroupLayout(tab5);
        tab5.setLayout(tab5Layout);
        tab5Layout.setHorizontalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        tab5Layout.setVerticalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab6.setBackground(new java.awt.Color(204, 255, 204));
        tab6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab6MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Môn được đăng kí");

        javax.swing.GroupLayout tab6Layout = new javax.swing.GroupLayout(tab6);
        tab6.setLayout(tab6Layout);
        tab6Layout.setHorizontalGroup(
            tab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab6Layout.setVerticalGroup(
            tab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab7.setBackground(new java.awt.Color(204, 255, 204));
        tab7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab7MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Quay lại");

        javax.swing.GroupLayout tab7Layout = new javax.swing.GroupLayout(tab7);
        tab7.setLayout(tab7Layout);
        tab7Layout.setHorizontalGroup(
            tab7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab7Layout.setVerticalGroup(
            tab7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jp3.setBackground(new java.awt.Color(204, 204, 255));

        lableTab3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lableTab3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab3.setText("Thêm sinh viên vào lớp học");

        lableIDTab3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableIDTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableIDTab3.setText("Nhập ID");

        lableNameTab3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableNameTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableNameTab3.setText("Nhập họ và tên");

        lableAddressTab3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableAddressTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableAddressTab3.setText("Nhập địa chỉ");

        cbGioiTinhTab3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbGioiTinhTab3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nữ", "Nam" }));

        lableGioiTinhTab3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableGioiTinhTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableGioiTinhTab3.setText("Chọn giới tính");

        lableClassTab3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableClassTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableClassTab3.setText("Chọn lớp");

        btnTab3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTab3.setText("Thêm");
        btnTab3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTab3ActionPerformed(evt);
            }
        });

        tfIDTab3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfIDTab3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tfNameTab3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfNameTab3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tfAddressTab3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfAddressTab3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        cbClassTab3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jp3Layout = new javax.swing.GroupLayout(jp3);
        jp3.setLayout(jp3Layout);
        jp3Layout.setHorizontalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(lableTab3))
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableIDTab3)
                            .addComponent(lableNameTab3)
                            .addComponent(lableAddressTab3)
                            .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lableClassTab3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lableGioiTinhTab3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(65, 65, 65)
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfIDTab3, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                                .addComponent(tfNameTab3)
                                .addComponent(tfAddressTab3))
                            .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbClassTab3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbGioiTinhTab3, javax.swing.GroupLayout.Alignment.LEADING, 0, 151, Short.MAX_VALUE))))
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(btnTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jp3Layout.setVerticalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lableTab3)
                .addGap(35, 35, 35)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lableIDTab3)
                            .addComponent(tfIDTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lableNameTab3)
                            .addComponent(tfNameTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lableAddressTab3)
                            .addComponent(tfAddressTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lableGioiTinhTab3)
                            .addComponent(cbGioiTinhTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(cbClassTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lableClassTab3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        jp6.setBackground(new java.awt.Color(204, 204, 255));

        tableTab6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã môn học", "Tên môn", "Số tín chỉ", "Được đăng kí"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTab6);

        lableTab6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lableTab6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab6.setText("Danh sách môn học được đăng kí");

        javax.swing.GroupLayout jp6Layout = new javax.swing.GroupLayout(jp6);
        jp6.setLayout(jp6Layout);
        jp6Layout.setHorizontalGroup(
            jp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp6Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(jp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp6Layout.createSequentialGroup()
                        .addComponent(lableTab6)
                        .addGap(211, 211, 211))))
        );
        jp6Layout.setVerticalGroup(
            jp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp6Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(lableTab6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jp5.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jp5Layout = new javax.swing.GroupLayout(jp5);
        jp5.setLayout(jp5Layout);
        jp5Layout.setHorizontalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
        );
        jp5Layout.setVerticalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        jp4.setBackground(new java.awt.Color(255, 204, 204));

        lableAddressTab4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableAddressTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableAddressTab4.setText("Nhập địa chỉ mới");

        cbGioiTinhTab4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbGioiTinhTab4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nữ", "Nam" }));

        lableGioiTinhTab4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableGioiTinhTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableGioiTinhTab4.setText("Chọn giới tính mới");

        lableClassTab4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableClassTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableClassTab4.setText("Chọn lớp mới");

        btnTab4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTab4.setText("Cập nhật");
        btnTab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTab4ActionPerformed(evt);
            }
        });

        tfIDTab4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfIDTab4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tfNameTab4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfNameTab4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tfAddressTab4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfAddressTab4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lableTab4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lableTab4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab4.setText("Cập nhật thông tin sinh viên");

        cbClassTab4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lableIDTab4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableIDTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableIDTab4.setText("Nhập ID");

        lableNameTab4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableNameTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableNameTab4.setText("Nhập họ và tên mới");

        javax.swing.GroupLayout jp4Layout = new javax.swing.GroupLayout(jp4);
        jp4.setLayout(jp4Layout);
        jp4Layout.setHorizontalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(lableTab4))
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableIDTab4)
                            .addComponent(lableNameTab4)
                            .addComponent(lableAddressTab4)
                            .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lableClassTab4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lableGioiTinhTab4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(35, 35, 35)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfNameTab4)
                            .addComponent(tfAddressTab4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                            .addComponent(cbClassTab4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbGioiTinhTab4, javax.swing.GroupLayout.Alignment.LEADING, 0, 151, Short.MAX_VALUE)
                            .addComponent(tfIDTab4)))
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(btnTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jp4Layout.setVerticalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lableTab4)
                .addGap(35, 35, 35)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lableIDTab4)
                            .addComponent(tfIDTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lableNameTab4)
                            .addComponent(tfNameTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lableAddressTab4)
                            .addComponent(tfAddressTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lableGioiTinhTab4)
                            .addComponent(cbGioiTinhTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(cbClassTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lableClassTab4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        jp2.setBackground(new java.awt.Color(255, 204, 204));

        tableTab2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableTab2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sinh viên", "Họ và tên", "Giới tính", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableTab2);

        tfTab2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfTab2.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lableTab2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lableTab2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab2.setText("Tìm kiếm sinh viên");

        lableIdTab2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableIdTab2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableIdTab2.setText("Nhập ID");

        btnTab2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTab2.setText("Tìm kiếm");
        btnTab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTab2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                        .addComponent(lableTab2)
                        .addGap(277, 277, 277))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                        .addComponent(btnTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(334, 334, 334))))
            .addGroup(jp2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addComponent(lableIdTab2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(244, 244, 244))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lableTab2)
                .addGap(34, 34, 34)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableIdTab2)
                    .addComponent(tfTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jp1.setBackground(new java.awt.Color(204, 204, 255));

        tableTab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sinh viên", "Họ và tên", "Giới tính", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableTab1);

        lableTab1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lableTab1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab1.setText("Danh sách sinh viên");

        comboboxTab1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboboxTab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxTab1ActionPerformed(evt);
            }
        });

        lableLuaChonTab1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableLuaChonTab1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableLuaChonTab1.setText("Chọn lớp");

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1Layout.createSequentialGroup()
                .addGap(0, 267, Short.MAX_VALUE)
                .addComponent(lableTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
            .addGroup(jp1Layout.createSequentialGroup()
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lableLuaChonTab1)
                        .addGap(85, 85, 85)
                        .addComponent(comboboxTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lableTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboboxTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableLuaChonTab1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        tab1.setBackground(new Color(204, 204, 255));
        tab2.setBackground(new Color(204, 255, 204));
        tab3.setBackground(new Color(204, 255, 204));
        tab4.setBackground(new Color(204, 255, 204));
        tab5.setBackground(new Color(204, 255, 204));
        tab6.setBackground(new Color(204, 255, 204));
        tab7.setBackground(new Color(204, 255, 204));

        jp1.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
        jp6.setVisible(false);

        showComboboxTab1();
    }//GEN-LAST:event_tab1MouseClicked

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        tab2.setBackground(new Color(204, 204, 255));
        tab1.setBackground(new Color(204, 255, 204));
        tab3.setBackground(new Color(204, 255, 204));
        tab4.setBackground(new Color(204, 255, 204));
        tab5.setBackground(new Color(204, 255, 204));
        tab6.setBackground(new Color(204, 255, 204));
        tab7.setBackground(new Color(204, 255, 204));

        jp2.setVisible(true);
        jp1.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
        jp6.setVisible(false);
    }//GEN-LAST:event_tab2MouseClicked

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        tab3.setBackground(new Color(204, 204, 255));
        tab2.setBackground(new Color(204, 255, 204));
        tab1.setBackground(new Color(204, 255, 204));
        tab4.setBackground(new Color(204, 255, 204));
        tab5.setBackground(new Color(204, 255, 204));
        tab6.setBackground(new Color(204, 255, 204));
        tab7.setBackground(new Color(204, 255, 204));

        jp3.setVisible(true);
        jp2.setVisible(false);
        jp1.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
        jp6.setVisible(false);

        tfIDTab3.setText("");
        tfNameTab3.setText("");
        tfAddressTab3.setText("");
        showComboboxTab3();
    }//GEN-LAST:event_tab3MouseClicked

    private void tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab4MouseClicked
        tab4.setBackground(new Color(204, 204, 255));
        tab2.setBackground(new Color(204, 255, 204));
        tab3.setBackground(new Color(204, 255, 204));
        tab1.setBackground(new Color(204, 255, 204));
        tab5.setBackground(new Color(204, 255, 204));
        tab6.setBackground(new Color(204, 255, 204));
        tab7.setBackground(new Color(204, 255, 204));

        jp4.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp1.setVisible(false);
        jp5.setVisible(false);
        jp6.setVisible(false);
        showComboboxTab4();

        tfNameTab4.setText("");
        tfIDTab4.setText("");
        tfAddressTab4.setText("");
    }//GEN-LAST:event_tab4MouseClicked

    private void tab5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab5MouseClicked
        tab5.setBackground(new Color(204, 204, 255));
        tab2.setBackground(new Color(204, 255, 204));
        tab3.setBackground(new Color(204, 255, 204));
        tab4.setBackground(new Color(204, 255, 204));
        tab1.setBackground(new Color(204, 255, 204));
        tab6.setBackground(new Color(204, 255, 204));
        tab7.setBackground(new Color(204, 255, 204));

        jp5.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp1.setVisible(false);
        jp6.setVisible(false);

        List<user> listUser = UserDAO.layDanhSachUser();

        for (user u : listUser) {
            if (u.getType() == 0) {
                u.setPassword("123456");
            }
        }
        for (user u : listUser) {
            if (u.getType() == 0) {
                if (UserDAO.capNhatThongTinUser(u) == false) {
                    JOptionPane.showMessageDialog(rootPane, "Reset mật khẩu thất bại!");
                    return;
                }
            }
        }
        JOptionPane.showMessageDialog(rootPane, "Reset mật khẩu thành công!");
    }//GEN-LAST:event_tab5MouseClicked

    private void tab6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab6MouseClicked
        tab6.setBackground(new Color(204, 204, 255));
        tab2.setBackground(new Color(204, 255, 204));
        tab3.setBackground(new Color(204, 255, 204));
        tab4.setBackground(new Color(204, 255, 204));
        tab1.setBackground(new Color(204, 255, 204));
        tab5.setBackground(new Color(204, 255, 204));
        tab7.setBackground(new Color(204, 255, 204));

        jp6.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp1.setVisible(false);
        jp5.setVisible(false);

        showTableTab6();
    }//GEN-LAST:event_tab6MouseClicked

    private void tab7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab7MouseClicked
        new GiaoVuGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tab7MouseClicked

    private void comboboxTab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxTab1ActionPerformed
        showTableTab1(comboboxTab1.getSelectedIndex());
    }//GEN-LAST:event_comboboxTab1ActionPerformed

    private void btnTab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTab2ActionPerformed
        modelTab2.setNumRows(0);
        String id = tfTab2.getText();
        if (id.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "MSSV không được để trống!");
            return;
        }
        student sv = StudentDAO.layThongTinSinhVien(id);
        if (sv == null) {
            JOptionPane.showMessageDialog(rootPane, "Sinh viên không tồn tại");
        } else {
            modelTab2.addRow(new Object[]{
                sv.getId(), sv.getName(), sv.getGioiTinh() == 1 ? "Nam" : "Nữ", sv.getAddress()
            });
        }
    }//GEN-LAST:event_btnTab2ActionPerformed

    private void btnTab3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTab3ActionPerformed
        String id = tfIDTab3.getText();
        String name = tfNameTab3.getText();
        String address = tfAddressTab3.getText();
        if (id.equals("") || name.equals("") || address.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Thông tin không được để trống!");
            return;
        }

        int gioiTinh = cbGioiTinhTab3.getSelectedIndex();
        String lopHoc = (String) cbClassTab3.getSelectedItem();

        if (StudentDAO.layThongTinSinhVien(id) != null) {
            JOptionPane.showMessageDialog(rootPane, "Mã số sinh viên đã tồn tại!");
        } else {
            student s = new student();
            s.setId(id);
            s.setName(name);
            s.setAddress(address);
            s.setGioiTinh(gioiTinh);
            s.getClass_student().add(new ClassPojo(lopHoc));
            if (StudentDAO.themSinhVien(s) == true) {
                JOptionPane.showMessageDialog(rootPane, "Thêm sinh viên vào lớp học thành công!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thêm sinh viên vào lớp học thất bại!");
            }
        }
    }//GEN-LAST:event_btnTab3ActionPerformed

    private void btnTab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTab4ActionPerformed
        String id = tfIDTab4.getText();
        String name = tfNameTab4.getText();
        String address = tfAddressTab4.getText();

        if (id.equals("") || name.equals("") || address.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Thông tin không được để trống!");
            return;
        }

        int gioiTinh = cbGioiTinhTab4.getSelectedIndex();
        String lopHoc = (String) cbClassTab4.getSelectedItem();

        if (StudentDAO.layThongTinSinhVien(id) == null) {
            JOptionPane.showMessageDialog(rootPane, "Mã số sinh viên không tồn tại!");
        } else {
            student s = StudentDAO.layThongTinSinhVien(id);
            s.setName(name);
            s.setAddress(address);
            s.setGioiTinh(gioiTinh);
            Set<ClassPojo> set = new HashSet<>();
            set.add(new ClassPojo(lopHoc));
            s.setClass_student(set);
            if (StudentDAO.capNhatThongTinStudent(s) == true) {
                JOptionPane.showMessageDialog(rootPane, "Cập nhật sinh viên vào lớp học thành công!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Cập nhật sinh viên vào lớp học thất bại!");
            }
        }
    }//GEN-LAST:event_btnTab4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSVTrongLopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSVTrongLopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSVTrongLopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSVTrongLopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSVTrongLopHoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTab2;
    private javax.swing.JButton btnTab3;
    private javax.swing.JButton btnTab4;
    private javax.swing.JComboBox<String> cbClassTab3;
    private javax.swing.JComboBox<String> cbClassTab4;
    private javax.swing.JComboBox<String> cbGioiTinhTab3;
    private javax.swing.JComboBox<String> cbGioiTinhTab4;
    private javax.swing.JComboBox<String> comboboxTab1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    private javax.swing.JPanel jp5;
    private javax.swing.JPanel jp6;
    private javax.swing.JLabel lableAddressTab3;
    private javax.swing.JLabel lableAddressTab4;
    private javax.swing.JLabel lableClassTab3;
    private javax.swing.JLabel lableClassTab4;
    private javax.swing.JLabel lableGioiTinhTab3;
    private javax.swing.JLabel lableGioiTinhTab4;
    private javax.swing.JLabel lableIDTab3;
    private javax.swing.JLabel lableIDTab4;
    private javax.swing.JLabel lableIdTab2;
    private javax.swing.JLabel lableLuaChonTab1;
    private javax.swing.JLabel lableNameTab3;
    private javax.swing.JLabel lableNameTab4;
    private javax.swing.JLabel lableTab1;
    private javax.swing.JLabel lableTab2;
    private javax.swing.JLabel lableTab3;
    private javax.swing.JLabel lableTab4;
    private javax.swing.JLabel lableTab6;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tab5;
    private javax.swing.JPanel tab6;
    private javax.swing.JPanel tab7;
    private javax.swing.JTable tableTab1;
    private javax.swing.JTable tableTab2;
    private javax.swing.JTable tableTab6;
    private javax.swing.JTextField tfAddressTab3;
    private javax.swing.JTextField tfAddressTab4;
    private javax.swing.JTextField tfIDTab3;
    private javax.swing.JTextField tfIDTab4;
    private javax.swing.JTextField tfNameTab3;
    private javax.swing.JTextField tfNameTab4;
    private javax.swing.JTextField tfTab2;
    // End of variables declaration//GEN-END:variables

    private void showComboboxTab3() {
        List<ClassPojo> listClass = ClassDAO.layDanhSachClass();
        for (ClassPojo c : listClass) {
            cbClassTab3.addItem(c.getMaLop());
        }
    }

    private void showComboboxTab4() {
        List<ClassPojo> listClass = ClassDAO.layDanhSachClass();
        for (ClassPojo c : listClass) {
            cbClassTab4.addItem(c.getMaLop());
        }
    }
}
