/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ClassDAO;
import dao.StudentDAO;
import dao.SubjectDAO;
import dao.UserDAO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import pojo.student;
import pojo.subject;
import pojo.user;
import pojo.ClassPojo;

/**
 *
 * @author HP
 */
public class QLSVTrongLop extends javax.swing.JFrame implements TableModelListener{

    /**
     * Creates new form QLSVTrongLop
     */
    private DefaultTableModel modelTab5;
    private DefaultTableModel modelTab1;
    private DefaultTableModel modelTab2;

    public QLSVTrongLop() {
        initComponents();
        //myInit();
        setLocationRelativeTo(null);
        modelTab5 = (DefaultTableModel) tableTab5.getModel();
        modelTab1 = (DefaultTableModel) tableTab1.getModel();
        modelTab2 = (DefaultTableModel) tableTab2.getModel();

        jp1.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);

    }
   

    public void showTableTab5() {
        modelTab5.setNumRows(0);
        List<subject> listSubject = SubjectDAO.layDanhSachSubject();

        for (subject sb : listSubject) {
            if (sb.getStudentsList().size() != 0) {
                modelTab5.addRow(new Object[]{
                    true, sb.getMaMonHoc(), sb.getName(), sb.getSoTinChi()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tab2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tab1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tab5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jpLogout = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lableReset = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jp1 = new javax.swing.JPanel();
        lableExit1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTab1 = new javax.swing.JTable();
        lableTab1 = new javax.swing.JLabel();
        comboboxTab1 = new javax.swing.JComboBox<>();
        lableLuaChonTab1 = new javax.swing.JLabel();
        jp2 = new javax.swing.JPanel();
        lableExit2 = new javax.swing.JLabel();
        btnTab2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTab2 = new javax.swing.JTable();
        tfTab2 = new javax.swing.JTextField();
        lableTab2 = new javax.swing.JLabel();
        lableIdTab2 = new javax.swing.JLabel();
        jp3 = new javax.swing.JPanel();
        lableExit3 = new javax.swing.JLabel();
        lableAddressTab3 = new javax.swing.JLabel();
        cbGioiTinhTab3 = new javax.swing.JComboBox<>();
        lableGioiTinhTab3 = new javax.swing.JLabel();
        lableClassTab3 = new javax.swing.JLabel();
        btnTab3 = new javax.swing.JButton();
        tfIDTab3 = new javax.swing.JTextField();
        tfNameTab3 = new javax.swing.JTextField();
        tfAddressTab3 = new javax.swing.JTextField();
        lableTab3 = new javax.swing.JLabel();
        cbClassTab3 = new javax.swing.JComboBox<>();
        lableIDTab3 = new javax.swing.JLabel();
        lableNameTab3 = new javax.swing.JLabel();
        jp4 = new javax.swing.JPanel();
        lableExit4 = new javax.swing.JLabel();
        tfAddressTab4 = new javax.swing.JTextField();
        lableTab4 = new javax.swing.JLabel();
        cbClassTab4 = new javax.swing.JComboBox<>();
        lableIDTab4 = new javax.swing.JLabel();
        lableAddressTab4 = new javax.swing.JLabel();
        lableNameTab4 = new javax.swing.JLabel();
        cbGioiTinhTab4 = new javax.swing.JComboBox<>();
        lableGioiTinhTab4 = new javax.swing.JLabel();
        lableClassTab4 = new javax.swing.JLabel();
        btnTab4 = new javax.swing.JButton();
        tfIDTab4 = new javax.swing.JTextField();
        tfNameTab4 = new javax.swing.JTextField();
        jp5 = new javax.swing.JPanel();
        lableExit5 = new javax.swing.JLabel();
        lableTab6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTab5 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(159, 226, 191));

        tab2.setBackground(new java.awt.Color(253, 254, 254));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tìm kiếm");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab1.setBackground(new java.awt.Color(253, 254, 254));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Xem danh sách");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab6.setBackground(new java.awt.Color(253, 254, 254));
        tab6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab6MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Quay lại");

        javax.swing.GroupLayout tab6Layout = new javax.swing.GroupLayout(tab6);
        tab6.setLayout(tab6Layout);
        tab6Layout.setHorizontalGroup(
            tab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab6Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab6Layout.setVerticalGroup(
            tab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab5.setBackground(new java.awt.Color(253, 254, 254));
        tab5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab5MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Môn được đăng kí");

        javax.swing.GroupLayout tab5Layout = new javax.swing.GroupLayout(tab5);
        tab5.setLayout(tab5Layout);
        tab5Layout.setHorizontalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab5Layout.setVerticalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab3.setBackground(new java.awt.Color(253, 254, 254));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Thêm sinh viên");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab4.setBackground(new java.awt.Color(253, 254, 254));
        tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab4MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Cập nhật thông tin");

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab4Layout.setVerticalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_teacher_50px.png"))); // NOI18N

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jpLogout.setBackground(new java.awt.Color(255, 102, 102));
        jpLogout.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jpLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_shutdown_25px_1.png"))); // NOI18N
        jpLogout.setText("Đăng xuất");
        jpLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpLogoutMouseClicked(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        lableReset.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lableReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_password_25px.png"))); // NOI18N
        lableReset.setText("Reset password sinh viên");
        lableReset.setToolTipText("Reset password của tất cả giáo vụ");
        lableReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableResetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableReset)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jpLogout))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(31, 31, 31)
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lableReset)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpLogout)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jp1.setBackground(new java.awt.Color(242, 243, 244));

        lableExit1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lableExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_35px.png"))); // NOI18N
        lableExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableExit1MouseClicked(evt);
            }
        });

        tableTab1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableTab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sinh viên", "Họ và tên", "Giới tính", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableTab1);

        lableTab1.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lableTab1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab1.setText("Danh sách sinh viên");

        comboboxTab1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboboxTab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxTab1ActionPerformed(evt);
            }
        });

        lableLuaChonTab1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableLuaChonTab1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableLuaChonTab1.setText("Chọn lớp");

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1Layout.createSequentialGroup()
                .addGap(0, 720, Short.MAX_VALUE)
                .addComponent(lableExit1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp1Layout.createSequentialGroup()
                    .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jp1Layout.createSequentialGroup()
                            .addGap(236, 236, 236)
                            .addComponent(lableTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jp1Layout.createSequentialGroup()
                            .addGap(111, 111, 111)
                            .addComponent(lableLuaChonTab1)
                            .addGap(85, 85, 85)
                            .addComponent(comboboxTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addComponent(lableExit1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp1Layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(lableTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)
                    .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboboxTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lableLuaChonTab1))
                    .addContainerGap(417, Short.MAX_VALUE)))
        );

        jp2.setBackground(new java.awt.Color(242, 243, 244));

        lableExit2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lableExit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_35px.png"))); // NOI18N
        lableExit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableExit2MouseClicked(evt);
            }
        });

        btnTab2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTab2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_find_user_male_25px.png"))); // NOI18N
        btnTab2.setText("Tìm kiếm");
        btnTab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTab2ActionPerformed(evt);
            }
        });

        tableTab2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableTab2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sinh viên", "Họ và tên", "Giới tính", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTab2.setSelectionForeground(new java.awt.Color(242, 243, 244));
        jScrollPane3.setViewportView(tableTab2);

        tfTab2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfTab2.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lableTab2.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lableTab2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab2.setText("Tìm kiếm sinh viên");

        lableIdTab2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableIdTab2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableIdTab2.setText("Nhập ID");

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                .addGap(0, 720, Short.MAX_VALUE)
                .addComponent(lableExit2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                        .addComponent(btnTab2)
                        .addGap(303, 303, 303))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                        .addComponent(lableTab2)
                        .addGap(254, 254, 254))))
            .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp2Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jp2Layout.createSequentialGroup()
                            .addComponent(lableIdTab2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(221, 221, 221))
                        .addGroup(jp2Layout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(47, Short.MAX_VALUE)))))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addComponent(lableExit2)
                .addGap(4, 4, 4)
                .addComponent(lableTab2)
                .addGap(103, 103, 103)
                .addComponent(btnTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 362, Short.MAX_VALUE))
            .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp2Layout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lableIdTab2)
                        .addComponent(tfTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(41, 41, 41)))
        );

        jp3.setBackground(new java.awt.Color(242, 243, 244));

        lableExit3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lableExit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_35px.png"))); // NOI18N
        lableExit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableExit3MouseClicked(evt);
            }
        });

        lableAddressTab3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableAddressTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableAddressTab3.setText("Nhập địa chỉ");

        cbGioiTinhTab3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbGioiTinhTab3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nữ", "Nam" }));

        lableGioiTinhTab3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableGioiTinhTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableGioiTinhTab3.setText("Chọn giới tính");

        lableClassTab3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableClassTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableClassTab3.setText("Chọn lớp");

        btnTab3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTab3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_add_25px.png"))); // NOI18N
        btnTab3.setText("Thêm");
        btnTab3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTab3ActionPerformed(evt);
            }
        });

        tfIDTab3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfIDTab3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tfNameTab3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNameTab3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tfAddressTab3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfAddressTab3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lableTab3.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lableTab3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab3.setText("Thêm sinh viên vào lớp học");

        cbClassTab3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lableIDTab3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableIDTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableIDTab3.setText("Nhập ID");

        lableNameTab3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableNameTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableNameTab3.setText("Nhập họ và tên");

        javax.swing.GroupLayout jp3Layout = new javax.swing.GroupLayout(jp3);
        jp3.setLayout(jp3Layout);
        jp3Layout.setHorizontalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3Layout.createSequentialGroup()
                .addGap(0, 720, Short.MAX_VALUE)
                .addComponent(lableExit3))
            .addGroup(jp3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(lableTab3))
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableIDTab3)
                            .addComponent(lableNameTab3)
                            .addComponent(lableAddressTab3)
                            .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lableClassTab3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lableGioiTinhTab3, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(65, 65, 65)
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfIDTab3)
                                .addComponent(tfNameTab3)
                                .addComponent(tfAddressTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbClassTab3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbGioiTinhTab3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(btnTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp3Layout.setVerticalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addComponent(lableExit3)
                .addGap(32, 32, 32)
                .addComponent(lableTab3)
                .addGap(35, 35, 35)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lableIDTab3)
                            .addComponent(tfIDTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lableNameTab3)
                            .addComponent(tfNameTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lableAddressTab3)
                            .addComponent(tfAddressTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lableGioiTinhTab3)
                            .addComponent(cbGioiTinhTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(cbClassTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lableClassTab3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        jp4.setBackground(new java.awt.Color(242, 243, 244));

        lableExit4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lableExit4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_35px.png"))); // NOI18N
        lableExit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableExit4MouseClicked(evt);
            }
        });

        tfAddressTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfAddressTab4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lableTab4.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lableTab4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab4.setText("Cập nhật thông tin sinh viên");

        cbClassTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lableIDTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableIDTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableIDTab4.setText("Nhập ID");

        lableAddressTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableAddressTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableAddressTab4.setText("Nhập địa chỉ mới");

        lableNameTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableNameTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableNameTab4.setText("Nhập họ và tên mới");

        cbGioiTinhTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbGioiTinhTab4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nữ", "Nam" }));

        lableGioiTinhTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableGioiTinhTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableGioiTinhTab4.setText("Chọn giới tính mới");

        lableClassTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableClassTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableClassTab4.setText("Chọn lớp mới");

        btnTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTab4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_update_user_25px_2.png"))); // NOI18N
        btnTab4.setText("Cập nhật");
        btnTab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTab4ActionPerformed(evt);
            }
        });

        tfIDTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfIDTab4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tfNameTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNameTab4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout jp4Layout = new javax.swing.GroupLayout(jp4);
        jp4.setLayout(jp4Layout);
        jp4Layout.setHorizontalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp4Layout.createSequentialGroup()
                .addGap(0, 720, Short.MAX_VALUE)
                .addComponent(lableExit4))
            .addGroup(jp4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(lableTab4))
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableIDTab4)
                            .addComponent(lableNameTab4)
                            .addComponent(lableAddressTab4)
                            .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lableClassTab4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lableGioiTinhTab4, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(35, 35, 35)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfNameTab4)
                            .addComponent(tfAddressTab4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbClassTab4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbGioiTinhTab4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfIDTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(btnTab4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp4Layout.setVerticalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addComponent(lableExit4)
                .addGap(53, 53, 53)
                .addComponent(lableTab4)
                .addGap(35, 35, 35)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lableIDTab4)
                            .addComponent(tfIDTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lableNameTab4)
                            .addComponent(tfNameTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lableAddressTab4)
                            .addComponent(tfAddressTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lableGioiTinhTab4)
                            .addComponent(cbGioiTinhTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(cbClassTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lableClassTab4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jp5.setBackground(new java.awt.Color(242, 243, 244));

        lableExit5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lableExit5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_35px.png"))); // NOI18N
        lableExit5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableExit5MouseClicked(evt);
            }
        });

        lableTab6.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lableTab6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab6.setText("Danh sách môn học được đăng kí");

        tableTab5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableTab5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Được đăng kí", "Mã môn học", "Tên môn học", "Số tín chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTab5);

        javax.swing.GroupLayout jp5Layout = new javax.swing.GroupLayout(jp5);
        jp5.setLayout(jp5Layout);
        jp5Layout.setHorizontalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lableExit5))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp5Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp5Layout.createSequentialGroup()
                        .addComponent(lableTab6)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );
        jp5Layout.setVerticalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp5Layout.createSequentialGroup()
                .addComponent(lableExit5)
                .addGap(24, 24, 24)
                .addComponent(lableTab6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lableExit5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableExit5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lableExit5MouseClicked

    private void lableExit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableExit4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lableExit4MouseClicked

    private void lableExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableExit1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lableExit1MouseClicked

    private void lableExit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableExit2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lableExit2MouseClicked

    private void lableExit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableExit3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lableExit3MouseClicked

    private void jpLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpLogoutMouseClicked
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jpLogoutMouseClicked

    private void lableResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableResetMouseClicked
        List<user> u = UserDAO.layDanhSachUser();

        for (user x : u) {
            if (x.getType() == 0) {
                x.setPassword("123456");
            }
        }

        for (user x : u) {
            if (x.getType() == 1) {
                if (UserDAO.capNhatThongTinUser(x) == false) {
                    JOptionPane.showMessageDialog(rootPane, "Reset mật khẩu sinh viên thất bại!");
                    return;
                }
            }
        }
        JOptionPane.showMessageDialog(rootPane, "Reset mật khẩu sinh viên thành công!");
    }//GEN-LAST:event_lableResetMouseClicked

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        jp1.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
        tab1.setBackground(new Color(204, 204, 255));

        tab2.setBackground(new Color(253, 254, 254));
        tab3.setBackground(new Color(253, 254, 254));
        tab4.setBackground(new Color(253, 254, 254));
        tab5.setBackground(new Color(253, 254, 254));
        showComboboxTab1();
    }//GEN-LAST:event_tab1MouseClicked

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        jp1.setVisible(false);
        jp2.setVisible(true);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
        tab2.setBackground(new Color(204, 204, 255));

        tab1.setBackground(new Color(253, 254, 254));
        tab3.setBackground(new Color(253, 254, 254));
        tab4.setBackground(new Color(253, 254, 254));
        tab5.setBackground(new Color(253, 254, 254));
    }//GEN-LAST:event_tab2MouseClicked

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(true);
        jp4.setVisible(false);
        jp5.setVisible(false);
        tab3.setBackground(new Color(204, 204, 255));

        tab2.setBackground(new Color(253, 254, 254));
        tab1.setBackground(new Color(253, 254, 254));
        tab4.setBackground(new Color(253, 254, 254));
        tab5.setBackground(new Color(253, 254, 254));
    }//GEN-LAST:event_tab3MouseClicked

    private void tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab4MouseClicked
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(true);
        tab4.setBackground(new Color(204, 204, 255));
        jp5.setVisible(false);

        tab2.setBackground(new Color(253, 254, 254));
        tab3.setBackground(new Color(253, 254, 254));
        tab1.setBackground(new Color(253, 254, 254));
        tab5.setBackground(new Color(253, 254, 254));
    }//GEN-LAST:event_tab4MouseClicked

    private void tab5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab5MouseClicked
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(true);
        tab5.setBackground(new Color(204, 204, 255));

        tab2.setBackground(new Color(253, 254, 254));
        tab3.setBackground(new Color(253, 254, 254));
        tab4.setBackground(new Color(253, 254, 254));
        tab1.setBackground(new Color(253, 254, 254));
        showTableTab5();
    }//GEN-LAST:event_tab5MouseClicked

    private void tab6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab6MouseClicked
        new GiaoVuGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tab6MouseClicked

    private void comboboxTab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxTab1ActionPerformed
        showTableTab1(comboboxTab1.getSelectedIndex());
    }//GEN-LAST:event_comboboxTab1ActionPerformed

    private void btnTab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTab2ActionPerformed
        modelTab2.setNumRows(0);
        String id = tfTab2.getText();
        if (id.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "MSSV không được để trống!");
            return;
        }
        student sv = StudentDAO.layThongTinSinhVien(id);
        if (sv == null) {
            JOptionPane.showMessageDialog(rootPane, "Sinh viên không tồn tại");
        } else {
            modelTab2.addRow(new Object[]{
                sv.getId(), sv.getName(), sv.getGioiTinh() == 1 ? "Nam" : "Nữ", sv.getAddress()
            });
        }
    }//GEN-LAST:event_btnTab2ActionPerformed

    private void btnTab3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTab3ActionPerformed
        String id = tfIDTab3.getText();
        String name = tfNameTab3.getText();
        String address = tfAddressTab3.getText();
        if (id.equals("") || name.equals("") || address.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Thông tin không được để trống!");
            return;
        }

        int gioiTinh = cbGioiTinhTab3.getSelectedIndex();
        String lopHoc = (String) cbClassTab3.getSelectedItem();

        if (StudentDAO.layThongTinSinhVien(id) != null) {
            JOptionPane.showMessageDialog(rootPane, "Mã số sinh viên đã tồn tại!");
        } else {
            student s = new student();
            s.setId(id);
            s.setName(name);
            s.setAddress(address);
            s.setGioiTinh(gioiTinh);
            s.getClass_student().add(new ClassPojo(lopHoc));
            if (StudentDAO.themSinhVien(s) == true) {
                JOptionPane.showMessageDialog(rootPane, "Thêm sinh viên vào lớp học thành công!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thêm sinh viên vào lớp học thất bại!");
            }
        }
    }//GEN-LAST:event_btnTab3ActionPerformed

    private void btnTab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTab4ActionPerformed
        String id = tfIDTab4.getText();
        String name = tfNameTab4.getText();
        String address = tfAddressTab4.getText();

        if (id.equals("") || name.equals("") || address.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Thông tin không được để trống!");
            return;
        }

        int gioiTinh = cbGioiTinhTab4.getSelectedIndex();
        String lopHoc = (String) cbClassTab4.getSelectedItem();

        if (StudentDAO.layThongTinSinhVien(id) == null) {
            JOptionPane.showMessageDialog(rootPane, "Mã số sinh viên không tồn tại!");
        } else {
            student s = StudentDAO.layThongTinSinhVien(id);
            s.setName(name);
            s.setAddress(address);
            s.setGioiTinh(gioiTinh);
            Set<ClassPojo> set = new HashSet<>();
            set.add(new ClassPojo(lopHoc));
            s.setClass_student(set);
            if (StudentDAO.capNhatThongTinStudent(s) == true) {
                JOptionPane.showMessageDialog(rootPane, "Cập nhật sinh viên vào lớp học thành công!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Cập nhật sinh viên vào lớp học thất bại!");
            }
        }
    }//GEN-LAST:event_btnTab4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSVTrongLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSVTrongLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSVTrongLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSVTrongLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSVTrongLop().setVisible(true);
            }
        });
    }

    public boolean checkMaLop(String a, List<pojo.ClassPojo> cl) {
        for (pojo.ClassPojo c : cl) {
            if (c.getMaLop().equals(a)) {
                return true;
            }
        }
        return false;
    }

    public void showTableTab1(int index) {
        modelTab1.setNumRows(0);
        List<student> listStudent = StudentDAO.layDanhSachStudent();

        if (index == 0) {
            for (student t : listStudent) {
                modelTab1.addRow(new Object[]{
                    t.getId(), t.getName(), t.getGioiTinh() == 1 ? "Nam" : "Nữ", t.getAddress()
                });
            }
        } else {
            for (student t : listStudent) {
                List<pojo.ClassPojo> myList = new ArrayList<>(t.getClass_student());
                if (checkMaLop(comboboxTab1.getItemAt(index), myList) == true) {
                    modelTab1.addRow(new Object[]{
                        t.getId(), t.getName(), t.getGioiTinh() == 1 ? "Nam" : "Nữ", t.getAddress()
                    });
                }
            }
        }
    }

    public void showComboboxTab1() {
        List<pojo.ClassPojo> listClass = ClassDAO.layDanhSachClass();
        comboboxTab1.addItem("Tất cả");
        for (pojo.ClassPojo c : listClass) {
            comboboxTab1.addItem(c.getMaLop());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTab2;
    private javax.swing.JButton btnTab3;
    private javax.swing.JButton btnTab4;
    private javax.swing.JComboBox<String> cbClassTab3;
    private javax.swing.JComboBox<String> cbClassTab4;
    private javax.swing.JComboBox<String> cbGioiTinhTab3;
    private javax.swing.JComboBox<String> cbGioiTinhTab4;
    private javax.swing.JComboBox<String> comboboxTab1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    private javax.swing.JPanel jp5;
    private javax.swing.JLabel jpLogout;
    private javax.swing.JLabel lableAddressTab3;
    private javax.swing.JLabel lableAddressTab4;
    private javax.swing.JLabel lableClassTab3;
    private javax.swing.JLabel lableClassTab4;
    private javax.swing.JLabel lableExit1;
    private javax.swing.JLabel lableExit2;
    private javax.swing.JLabel lableExit3;
    private javax.swing.JLabel lableExit4;
    private javax.swing.JLabel lableExit5;
    private javax.swing.JLabel lableGioiTinhTab3;
    private javax.swing.JLabel lableGioiTinhTab4;
    private javax.swing.JLabel lableIDTab3;
    private javax.swing.JLabel lableIDTab4;
    private javax.swing.JLabel lableIdTab2;
    private javax.swing.JLabel lableLuaChonTab1;
    private javax.swing.JLabel lableNameTab3;
    private javax.swing.JLabel lableNameTab4;
    private javax.swing.JLabel lableReset;
    private javax.swing.JLabel lableTab1;
    private javax.swing.JLabel lableTab2;
    private javax.swing.JLabel lableTab3;
    private javax.swing.JLabel lableTab4;
    private javax.swing.JLabel lableTab6;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tab5;
    private javax.swing.JPanel tab6;
    private javax.swing.JTable tableTab1;
    private javax.swing.JTable tableTab2;
    private javax.swing.JTable tableTab5;
    private javax.swing.JTextField tfAddressTab3;
    private javax.swing.JTextField tfAddressTab4;
    private javax.swing.JTextField tfIDTab3;
    private javax.swing.JTextField tfIDTab4;
    private javax.swing.JTextField tfNameTab3;
    private javax.swing.JTextField tfNameTab4;
    private javax.swing.JTextField tfTab2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void tableChanged(TableModelEvent e) {
       return;
    }
}
