/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.TeacherDAO;
import dao.UserDAO;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.teacher;
import pojo.user;

/**
 *
 * @author HP
 */
public class QLTaiKhoan extends javax.swing.JFrame {

    /**
     * Creates new form QLTaiKhoan
     */
    DefaultTableModel modelTab1;
    DefaultTableModel modelTab2;

    public QLTaiKhoan() {
        initComponents();
        modelTab1 = (DefaultTableModel) tableTab1.getModel();
        modelTab2 = (DefaultTableModel) tableTab2.getModel();
        setLocationRelativeTo(null);

        jp1.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
        jp6.setVisible(false);
    }

    public void showTableTab1() {

        modelTab1.setNumRows(0);
        List<teacher> listTeacher = TeacherDAO.layDanhSachTeacher();
        for (teacher t : listTeacher) {
            modelTab1.addRow(new Object[]{
                t.getName(), t.getEmail(), t.getPhoneNumber(), t.getAddress(), t.getUsername()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tab5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tab6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tab7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jp1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTab1 = new javax.swing.JTable();
        lableTab1 = new javax.swing.JLabel();
        jp6 = new javax.swing.JPanel();
        lableTab6 = new javax.swing.JLabel();
        lableUsernameTab6 = new javax.swing.JLabel();
        btnDeleteTab6 = new javax.swing.JButton();
        cbTab6 = new javax.swing.JComboBox<>();
        jp5 = new javax.swing.JPanel();
        jp4 = new javax.swing.JPanel();
        btnUpdateTab4 = new javax.swing.JButton();
        lablePhoneNumberTab4 = new javax.swing.JLabel();
        lableAddressTab4 = new javax.swing.JLabel();
        tfNameTab4 = new javax.swing.JTextField();
        tfEmailTab4 = new javax.swing.JTextField();
        tfPhoneNumberTab4 = new javax.swing.JTextField();
        lableTab4 = new javax.swing.JLabel();
        lableNameTab4 = new javax.swing.JLabel();
        tfAddressTab4 = new javax.swing.JTextField();
        lableEmailTab4 = new javax.swing.JLabel();
        btnPassTab4 = new javax.swing.JButton();
        jp3 = new javax.swing.JPanel();
        lableTab3 = new javax.swing.JLabel();
        tfPhoneNumberTab3 = new javax.swing.JTextField();
        lableNameTab3 = new javax.swing.JLabel();
        tfAddressTab3 = new javax.swing.JTextField();
        lableEmailTab3 = new javax.swing.JLabel();
        tfUsernameTab3 = new javax.swing.JTextField();
        lablePhoneNumberTab3 = new javax.swing.JLabel();
        lableAddressTab3 = new javax.swing.JLabel();
        btnThemTab3 = new javax.swing.JButton();
        lableUsernameTab3 = new javax.swing.JLabel();
        lablePasswordTab3 = new javax.swing.JLabel();
        tfNameTab3 = new javax.swing.JTextField();
        tfEmailTab3 = new javax.swing.JTextField();
        lablePasswordTab3_1 = new javax.swing.JLabel();
        jpPassTab3 = new javax.swing.JPasswordField();
        jpPassTab3_1 = new javax.swing.JPasswordField();
        jp2 = new javax.swing.JPanel();
        lableTab2 = new javax.swing.JLabel();
        tfTab2 = new javax.swing.JTextField();
        btnFindTab2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTab2 = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý tài khoản");

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        tab1.setBackground(new java.awt.Color(51, 255, 204));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Xem danh sách");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab3.setBackground(new java.awt.Color(51, 255, 204));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Thêm tài khoản");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab2.setBackground(new java.awt.Color(51, 255, 204));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Tìm kiếm tài khoản");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab4.setBackground(new java.awt.Color(51, 255, 204));
        tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab4MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Cập nhật thông tin");

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab4Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(56, 56, 56))
        );
        tab4Layout.setVerticalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab5.setBackground(new java.awt.Color(51, 255, 204));
        tab5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab5MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Reset mật khẩu");

        javax.swing.GroupLayout tab5Layout = new javax.swing.GroupLayout(tab5);
        tab5.setLayout(tab5Layout);
        tab5Layout.setHorizontalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab5Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab5Layout.setVerticalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab6.setBackground(new java.awt.Color(51, 255, 204));
        tab6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab6MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Xóa tài khoản");

        javax.swing.GroupLayout tab6Layout = new javax.swing.GroupLayout(tab6);
        tab6.setLayout(tab6Layout);
        tab6Layout.setHorizontalGroup(
            tab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        tab6Layout.setVerticalGroup(
            tab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab7.setBackground(new java.awt.Color(51, 255, 204));
        tab7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab7MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Quay lại");

        javax.swing.GroupLayout tab7Layout = new javax.swing.GroupLayout(tab7);
        tab7.setLayout(tab7Layout);
        tab7Layout.setHorizontalGroup(
            tab7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        tab7Layout.setVerticalGroup(
            tab7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp1.setBackground(new java.awt.Color(255, 204, 204));

        tableTab1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tableTab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ và tên", "Email", "Số điện thoại", "Địa chỉ", "User"
            }
        ));
        jScrollPane1.setViewportView(tableTab1);

        lableTab1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lableTab1.setForeground(new java.awt.Color(255, 0, 0));
        lableTab1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab1.setText("Danh sách tài khoản giáo vụ");

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lableTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lableTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jp6.setBackground(new java.awt.Color(255, 204, 204));

        lableTab6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lableTab6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab6.setText("Xóa tài khoản");

        lableUsernameTab6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lableUsernameTab6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableUsernameTab6.setText("Chọn username");

        btnDeleteTab6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDeleteTab6.setText("Xóa");
        btnDeleteTab6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTab6ActionPerformed(evt);
            }
        });

        cbTab6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jp6Layout = new javax.swing.GroupLayout(jp6);
        jp6.setLayout(jp6Layout);
        jp6Layout.setHorizontalGroup(
            jp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp6Layout.createSequentialGroup()
                .addGroup(jp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp6Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lableUsernameTab6)
                        .addGap(62, 62, 62)
                        .addComponent(cbTab6, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp6Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(btnDeleteTab6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(231, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lableTab6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
        );
        jp6Layout.setVerticalGroup(
            jp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp6Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lableTab6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableUsernameTab6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTab6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addComponent(btnDeleteTab6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jp5.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jp5Layout = new javax.swing.GroupLayout(jp5);
        jp5.setLayout(jp5Layout);
        jp5Layout.setHorizontalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jp5Layout.setVerticalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jp4.setBackground(new java.awt.Color(204, 204, 255));

        btnUpdateTab4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdateTab4.setText("Update");
        btnUpdateTab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTab4ActionPerformed(evt);
            }
        });

        lablePhoneNumberTab4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lablePhoneNumberTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lablePhoneNumberTab4.setText("Số điện thoại");

        lableAddressTab4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lableAddressTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableAddressTab4.setText("Địa chỉ");

        tfNameTab4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfNameTab4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tfEmailTab4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfEmailTab4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tfPhoneNumberTab4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfPhoneNumberTab4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lableTab4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lableTab4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab4.setText("CẬP NHẬT THÔNG TIN");

        lableNameTab4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lableNameTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableNameTab4.setText("Họ và tên");

        tfAddressTab4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfAddressTab4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lableEmailTab4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lableEmailTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableEmailTab4.setText("Email");

        btnPassTab4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPassTab4.setText("Đổi mật khẩu");
        btnPassTab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassTab4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp4Layout = new javax.swing.GroupLayout(jp4);
        jp4.setLayout(jp4Layout);
        jp4Layout.setHorizontalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp4Layout.createSequentialGroup()
                                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lableNameTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lableEmailTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lablePhoneNumberTab4)
                                    .addComponent(lableAddressTab4))
                                .addGap(49, 49, 49)
                                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfAddressTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPhoneNumberTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfEmailTab4)
                                        .addComponent(tfNameTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jp4Layout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(lableTab4))))
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(btnUpdateTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(btnPassTab4)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jp4Layout.setVerticalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lableTab4)
                .addGap(39, 39, 39)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNameTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableNameTab4))
                .addGap(18, 18, 18)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmailTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableEmailTab4))
                .addGap(18, 18, 18)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPhoneNumberTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lablePhoneNumberTab4))
                .addGap(18, 18, 18)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAddressTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableAddressTab4))
                .addGap(65, 65, 65)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPassTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jp3.setBackground(new java.awt.Color(255, 204, 204));

        lableTab3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lableTab3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab3.setText("THÊM TÀI KHOẢN");

        tfPhoneNumberTab3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfPhoneNumberTab3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lableNameTab3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lableNameTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableNameTab3.setText("Họ và tên");

        tfAddressTab3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfAddressTab3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lableEmailTab3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lableEmailTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableEmailTab3.setText("Email");

        tfUsernameTab3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfUsernameTab3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lablePhoneNumberTab3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lablePhoneNumberTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lablePhoneNumberTab3.setText("Số điện thoại");

        lableAddressTab3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lableAddressTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableAddressTab3.setText("Địa chỉ");

        btnThemTab3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThemTab3.setText("Thêm");
        btnThemTab3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTab3ActionPerformed(evt);
            }
        });

        lableUsernameTab3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lableUsernameTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableUsernameTab3.setText("Username");

        lablePasswordTab3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lablePasswordTab3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lablePasswordTab3.setText("Password");

        tfNameTab3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfNameTab3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tfEmailTab3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfEmailTab3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lablePasswordTab3_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lablePasswordTab3_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lablePasswordTab3_1.setText("Nhập lại password");

        jpPassTab3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jpPassTab3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jpPassTab3_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jpPassTab3_1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout jp3Layout = new javax.swing.GroupLayout(jp3);
        jp3.setLayout(jp3Layout);
        jp3Layout.setHorizontalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(btnThemTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp3Layout.createSequentialGroup()
                                .addComponent(lableNameTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(tfNameTab3))
                            .addGroup(jp3Layout.createSequentialGroup()
                                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lableEmailTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lablePhoneNumberTab3)
                                    .addComponent(lableAddressTab3)
                                    .addComponent(lableUsernameTab3)
                                    .addComponent(lablePasswordTab3)
                                    .addComponent(lablePasswordTab3_1))
                                .addGap(21, 21, 21)
                                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpPassTab3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jpPassTab3)
                                        .addComponent(tfUsernameTab3)
                                        .addComponent(tfAddressTab3)
                                        .addComponent(tfPhoneNumberTab3)
                                        .addComponent(tfEmailTab3)))))))
                .addGap(112, 112, 112))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3Layout.createSequentialGroup()
                .addComponent(lableTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
        );
        jp3Layout.setVerticalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lableTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNameTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableNameTab3))
                .addGap(17, 17, 17)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmailTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableEmailTab3))
                .addGap(16, 16, 16)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPhoneNumberTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lablePhoneNumberTab3))
                .addGap(18, 18, 18)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAddressTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableAddressTab3))
                .addGap(17, 17, 17)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUsernameTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableUsernameTab3))
                .addGap(17, 17, 17)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpPassTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lablePasswordTab3))
                .addGap(15, 15, 15)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpPassTab3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lablePasswordTab3_1))
                .addGap(14, 14, 14)
                .addComponent(btnThemTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jp2.setBackground(new java.awt.Color(153, 153, 255));

        lableTab2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lableTab2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableTab2.setText("Nhập username");

        tfTab2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfTab2.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnFindTab2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFindTab2.setText("Tìm");
        btnFindTab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindTab2ActionPerformed(evt);
            }
        });

        tableTab2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ và tên", "Email", "Số điện thoại", "Địa chỉ", "Username"
            }
        ));
        jScrollPane2.setViewportView(tableTab2);

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addComponent(lableTab2)
                                .addGap(76, 76, 76)
                                .addComponent(tfTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(btnFindTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableTab2))
                .addGap(26, 26, 26)
                .addComponent(btnFindTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        jp1.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
        jp6.setVisible(false);
        tab1.setBackground(new Color(204, 204, 255));

        tab2.setBackground(new Color(51, 255, 204));
        tab3.setBackground(new Color(51, 255, 204));
        tab4.setBackground(new Color(51, 255, 204));
        tab5.setBackground(new Color(51, 255, 204));
        tab6.setBackground(new Color(51, 255, 204));

        showTableTab1();
    }//GEN-LAST:event_tab1MouseClicked

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        jp1.setVisible(false);
        jp2.setVisible(true);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
        jp6.setVisible(false);
        tab2.setBackground(new Color(204, 204, 255));

        tab1.setBackground(new Color(51, 255, 204));
        tab3.setBackground(new Color(51, 255, 204));
        tab4.setBackground(new Color(51, 255, 204));
        tab5.setBackground(new Color(51, 255, 204));
        tab6.setBackground(new Color(51, 255, 204));

    }//GEN-LAST:event_tab2MouseClicked

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(true);
        jp4.setVisible(false);
        jp5.setVisible(false);
        jp6.setVisible(false);
        tab3.setBackground(new Color(204, 204, 255));

        tab2.setBackground(new Color(51, 255, 204));
        tab1.setBackground(new Color(51, 255, 204));
        tab4.setBackground(new Color(51, 255, 204));
        tab5.setBackground(new Color(51, 255, 204));
        tab6.setBackground(new Color(51, 255, 204));
    }//GEN-LAST:event_tab3MouseClicked

    private void tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab4MouseClicked
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(true);
        jp5.setVisible(false);
        tab4.setBackground(new Color(204, 204, 255));
        jp6.setVisible(false);

        tab2.setBackground(new Color(51, 255, 204));
        tab3.setBackground(new Color(51, 255, 204));
        tab1.setBackground(new Color(51, 255, 204));
        tab5.setBackground(new Color(51, 255, 204));
        tab6.setBackground(new Color(51, 255, 204));
    }//GEN-LAST:event_tab4MouseClicked

    private void tab5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab5MouseClicked
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(true);
        jp6.setVisible(false);
        tab5.setBackground(new Color(204, 204, 255));

        tab2.setBackground(new Color(51, 255, 204));
        tab3.setBackground(new Color(51, 255, 204));
        tab4.setBackground(new Color(51, 255, 204));
        tab1.setBackground(new Color(51, 255, 204));
        tab6.setBackground(new Color(51, 255, 204));

        List<user> u = UserDAO.layDanhSachUser();

        for (user x : u) {
            if (x.getType() == 1) {
                x.setPassword("123456");
            }
        }

        for (user x : u) {
            if (x.getType() == 1) {
                if (UserDAO.capNhatThongTinUser(x) == false) {
                    JOptionPane.showMessageDialog(rootPane, "Reset mật khẩu thất bại!");
                    return;
                }
            }
        }
        JOptionPane.showMessageDialog(rootPane, "Reset mật khẩu thành công!");
    }//GEN-LAST:event_tab5MouseClicked

    private void tab6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab6MouseClicked
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
        jp6.setVisible(true);
        tab6.setBackground(new Color(204, 204, 255));

        tab2.setBackground(new Color(51, 255, 204));
        tab3.setBackground(new Color(51, 255, 204));
        tab4.setBackground(new Color(51, 255, 204));
        tab5.setBackground(new Color(51, 255, 204));
        tab1.setBackground(new Color(51, 255, 204));
        
        showComboboxTab6();
    }//GEN-LAST:event_tab6MouseClicked

    private void btnFindTab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindTab2ActionPerformed
        List<teacher> listTeacher = TeacherDAO.layDanhSachTeacher();
        String username = tfTab2.getText();
        for (teacher t : listTeacher) {
            if (username.equals(t.getUsername())) {
                modelTab2.addRow(new Object[]{
                    t.getName(), t.getEmail(), t.getPhoneNumber(), t.getAddress(), t.getUsername()
                });
                return;
            }
        }
        JOptionPane.showMessageDialog(rootPane, "username không tồn tại!");
    }//GEN-LAST:event_btnFindTab2ActionPerformed

    private void btnThemTab3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTab3ActionPerformed
        String name = tfNameTab3.getText();
        String email = tfEmailTab3.getText();
        String address = tfAddressTab3.getText();
        String phoneNumber = tfPhoneNumberTab3.getText();
        String username = tfUsernameTab3.getText();
        String password = jpPassTab3.getText();
        String password_1 = jpPassTab3_1.getText();

        if (name.equals("") || email.equals("") || address.equals("") || phoneNumber.equals("")
                || username.equals("") || password.equals("") || password_1.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Bạn phải điền đầy đủ thông tin!");
            return;
        }

        if (!password.equals(password_1)) {
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu không khớp!");
        } else if (TeacherDAO.layThongTinTeacher(username) != null) {
            JOptionPane.showMessageDialog(rootPane, "username đã tồn tại");
        } else {
            teacher t = new teacher(username, name, email, address, phoneNumber);
            user u = new user(username, password, 1, null);
            if (TeacherDAO.addTeacher(t) == true && UserDAO.addUser(u) == true) {
                JOptionPane.showMessageDialog(rootPane, "Thêm tài khoản thành công");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thêm tài khoản thất bại");
            }
        }
    }//GEN-LAST:event_btnThemTab3ActionPerformed

    private void btnUpdateTab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTab4ActionPerformed
        String name = tfNameTab4.getText();
        String email = tfEmailTab4.getText();
        String address = tfAddressTab4.getText();
        String phoneNumber = tfPhoneNumberTab4.getText();
        if (email.equals("") || name.equals("") || address.equals("") || phoneNumber.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Bạn phải nhập đầy đủ thông tin!");
            return;
        }

        teacher t = new teacher(login.staticUsername, name, email, address, phoneNumber);

        if (TeacherDAO.capNhatThongTinTeacher(t)) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin thành công!");
        } else {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin thất bại!");
        }
    }//GEN-LAST:event_btnUpdateTab4ActionPerformed

    private void btnPassTab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassTab4ActionPerformed
        new changePass().setVisible(true);
    }//GEN-LAST:event_btnPassTab4ActionPerformed

    private void btnDeleteTab6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTab6ActionPerformed
        String username = cbTab6.getSelectedItem().toString();

        if (TeacherDAO.xoaTeacher(username) == true && UserDAO.xoaUser(username) == true) {
            JOptionPane.showMessageDialog(rootPane, "Xóa tài khoản thành công");
        } else {
            JOptionPane.showMessageDialog(rootPane, "username không tồn tại");
        }
    }//GEN-LAST:event_btnDeleteTab6ActionPerformed

    private void tab7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab7MouseClicked
        new GiaoVuGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tab7MouseClicked

    public void showComboboxTab6() {
        cbTab6.removeAllItems();
        List<user> list = UserDAO.layDanhSachUser();
        for (user c : list) {
            if (c.getType() == 1) {
                cbTab6.addItem(c.getUsername());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLTaiKhoan.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLTaiKhoan.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLTaiKhoan.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLTaiKhoan.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteTab6;
    private javax.swing.JButton btnFindTab2;
    private javax.swing.JButton btnPassTab4;
    private javax.swing.JButton btnThemTab3;
    private javax.swing.JButton btnUpdateTab4;
    private javax.swing.JComboBox<String> cbTab6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    private javax.swing.JPanel jp5;
    private javax.swing.JPanel jp6;
    private javax.swing.JPasswordField jpPassTab3;
    private javax.swing.JPasswordField jpPassTab3_1;
    private javax.swing.JLabel lableAddressTab3;
    private javax.swing.JLabel lableAddressTab4;
    private javax.swing.JLabel lableEmailTab3;
    private javax.swing.JLabel lableEmailTab4;
    private javax.swing.JLabel lableNameTab3;
    private javax.swing.JLabel lableNameTab4;
    private javax.swing.JLabel lablePasswordTab3;
    private javax.swing.JLabel lablePasswordTab3_1;
    private javax.swing.JLabel lablePhoneNumberTab3;
    private javax.swing.JLabel lablePhoneNumberTab4;
    private javax.swing.JLabel lableTab1;
    private javax.swing.JLabel lableTab2;
    private javax.swing.JLabel lableTab3;
    private javax.swing.JLabel lableTab4;
    private javax.swing.JLabel lableTab6;
    private javax.swing.JLabel lableUsernameTab3;
    private javax.swing.JLabel lableUsernameTab6;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tab5;
    private javax.swing.JPanel tab6;
    private javax.swing.JPanel tab7;
    private javax.swing.JTable tableTab1;
    private javax.swing.JTable tableTab2;
    private javax.swing.JTextField tfAddressTab3;
    private javax.swing.JTextField tfAddressTab4;
    private javax.swing.JTextField tfEmailTab3;
    private javax.swing.JTextField tfEmailTab4;
    private javax.swing.JTextField tfNameTab3;
    private javax.swing.JTextField tfNameTab4;
    private javax.swing.JTextField tfPhoneNumberTab3;
    private javax.swing.JTextField tfPhoneNumberTab4;
    private javax.swing.JTextField tfTab2;
    private javax.swing.JTextField tfUsernameTab3;
    // End of variables declaration//GEN-END:variables
}
