/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.CourseDAO;
import dao.DangKiHocPhanDAO;
import dao.StudentDAO;
import dao.semesterDAO;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.course;
import pojo.dangKiHocPhan;
import pojo.semester;
import pojo.student;
import pojo.user;

/**
 *
 * @author HP
 */
public class SinhVienGUI extends javax.swing.JFrame {

    /**
     * Creates new form SinhVienGUI
     */
    private DefaultTableModel modelTab1;
    private DefaultTableModel modelTab2;
    private DefaultTableModel modelTab3;
    private String today;
    private dangKiHocPhan c = DangKiHocPhanDAO.layThongTinDangKiHPHT();

    public SinhVienGUI() {
        initComponents();
        setLocationRelativeTo(null);
        modelTab1 = (DefaultTableModel) tableTab1.getModel();
        modelTab2 = (DefaultTableModel) tableTab2.getModel();
        modelTab3 = (DefaultTableModel) tableTab3.getModel();

        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp0.setVisible(false);
        jp7.setVisible(true);

        semester s = semesterDAO.layThongTinSemesterHocKiHT();
        if (s != null) {
            lable.setText(s.getName() + " - " + s.getYear());
        }

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        LocalDateTime now = LocalDateTime.now();
        today = dtf.format(now);

    }

    public int checkNgayLonHon(String[] s1, String[] s2) {
        if (s1[2].equals(s2[2]) && s1[1].equals(s2[1]) && s1[0].equals(s2[0])) {
            return 0;
        }

        for (int i = 2; i >= 0; i--) {
            if ((s1[i]).compareTo(s2[i]) < 0) {
                return -1;
            } else if ((s1[i]).compareTo(s2[i]) > 0) {
                return 1;
            }
        }
        return 1;
    }

    public void showTableTab1() {
        modelTab1.setNumRows(0);
        List<course> listCourse = CourseDAO.layDanhSachCourse();
        if (listCourse == null) {
            return;
        }
        for (course c : listCourse) {
            int slotCon = c.getMaxSlot() - c.getListStudent().size();
            modelTab1.addRow(new Object[]{
                c.getMaMonHoc(), c.getTenMon(), c.getSoTinChi(), c.getGvlt(), c.getTenPhongHoc(), c.getNgayHoc(),
                c.getCaHoc(), slotCon, false
            });
        }
    }

    public void showTableTab2() {
        modelTab2.setNumRows(0);
        student st = StudentDAO.layThongTinSinhVien(login.staticUsername);
        if (st == null) {
            return;
        }

        List<course> listCourse = new ArrayList<>(st.getCourse_student());
        for (course c : listCourse) {
            modelTab2.addRow(new Object[]{
                c.getMaMonHoc(), c.getTenMon(), c.getSoTinChi(), c.getGvlt(), c.getTenPhongHoc(), c.getNgayHoc(),
                c.getCaHoc()
            });
        }
    }

    public void showTableTab3() {
        modelTab3.setNumRows(0);
        student st = StudentDAO.layThongTinSinhVien(login.staticUsername);
        if (st == null) {
            return;
        }

        List<course> listCourse = new ArrayList<>(st.getCourse_student());
        for (course c : listCourse) {
            modelTab3.addRow(new Object[]{
                c.getMaMonHoc(), c.getTenMon(), c.getSoTinChi(), c.getGvlt(), c.getTenPhongHoc(), c.getNgayHoc(),
                c.getCaHoc(), false
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tab2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tab1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tab0 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lable = new javax.swing.JLabel();
        tab7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jp1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTab1 = new javax.swing.JTable();
        btnTab1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lableExit1 = new javax.swing.JLabel();
        lable1Tab1 = new javax.swing.JLabel();
        lable2Tab1 = new javax.swing.JLabel();
        jp7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfIDTab7 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfNameTab7 = new javax.swing.JTextField();
        tfAddressTab7 = new javax.swing.JTextField();
        cboxNamTab7 = new javax.swing.JCheckBox();
        cboxNuTab7 = new javax.swing.JCheckBox();
        lableExit = new javax.swing.JLabel();
        jp2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTab2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lableExit2 = new javax.swing.JLabel();
        jp0 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfNameTab0 = new javax.swing.JTextField();
        tfAddressTab0 = new javax.swing.JTextField();
        btnUpdateTab0 = new javax.swing.JButton();
        btnChangePassTab0 = new javax.swing.JButton();
        cbTab0 = new javax.swing.JComboBox<>();
        lableExit4 = new javax.swing.JLabel();
        jp3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTab3 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnTab3 = new javax.swing.JButton();
        lableExit3 = new javax.swing.JLabel();
        lable1Tab3 = new javax.swing.JLabel();
        lable2Tab3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giao diện sinh viên");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(159, 226, 191));

        tab2.setBackground(new java.awt.Color(253, 254, 254));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Danh sách đăng kí");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        tab4.setBackground(new java.awt.Color(253, 254, 254));
        tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab4MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Đăng xuất");

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab4Layout.setVerticalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        tab1.setBackground(new java.awt.Color(253, 254, 254));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Đăng kí học phần");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        tab3.setBackground(new java.awt.Color(253, 254, 254));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Xóa học phần");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        tab0.setBackground(new java.awt.Color(253, 254, 254));
        tab0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab0MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Cập nhật thông tin");

        javax.swing.GroupLayout tab0Layout = new javax.swing.GroupLayout(tab0);
        tab0.setLayout(tab0Layout);
        tab0Layout.setHorizontalGroup(
            tab0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab0Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        tab0Layout.setVerticalGroup(
            tab0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_student_male_80px.png"))); // NOI18N

        lable.setFont(new java.awt.Font("Segoe UI", 2, 22)); // NOI18N
        lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tab7.setBackground(new java.awt.Color(253, 254, 254));
        tab7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab7MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Thông tin cá nhân");

        javax.swing.GroupLayout tab7Layout = new javax.swing.GroupLayout(tab7);
        tab7.setLayout(tab7Layout);
        tab7Layout.setHorizontalGroup(
            tab7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab7Layout.setVerticalGroup(
            tab7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel13)
                .addGap(0, 110, Short.MAX_VALUE))
            .addComponent(tab7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lable, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lable, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp1.setBackground(new java.awt.Color(242, 243, 244));

        tableTab1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableTab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã môn", "Tên môn", "Số tín chỉ", "Giáo viên LT", "Phòng học", "Ngày học", "Ca học", "Slot còn", "Đăng kí"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTab1);

        btnTab1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTab1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_registration_28px.png"))); // NOI18N
        btnTab1.setText("Đăng kí");
        btnTab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTab1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Đăng kí học phần");

        lableExit1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lableExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_35px.png"))); // NOI18N
        lableExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableExit1MouseClicked(evt);
            }
        });

        lable1Tab1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lable1Tab1.setText("a");

        lable2Tab1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lable2Tab1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lable2Tab1.setText("b");

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(342, 342, 342)
                        .addComponent(lableExit1))
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jp1Layout.createSequentialGroup()
                                .addComponent(lable1Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114)
                                .addComponent(lable2Tab1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1Layout.createSequentialGroup()
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lableExit1)
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lable1Tab1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnTab1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addComponent(lable2Tab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(85, 85, 85))
        );

        jp7.setBackground(new java.awt.Color(242, 243, 244));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("ID");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Thông tin chi tiết");

        tfIDTab7.setEditable(false);
        tfIDTab7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Họ và tên");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Giới tính");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Địa chỉ");

        tfNameTab7.setEditable(false);
        tfNameTab7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tfAddressTab7.setEditable(false);
        tfAddressTab7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cboxNamTab7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboxNamTab7.setText("Nam");
        cboxNamTab7.setBorderPainted(true);
        cboxNamTab7.setEnabled(false);

        cboxNuTab7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboxNuTab7.setText("Nữ");
        cboxNuTab7.setBorderPainted(true);
        cboxNuTab7.setEnabled(false);

        lableExit.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lableExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_35px.png"))); // NOI18N
        lableExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp7Layout = new javax.swing.GroupLayout(jp7);
        jp7.setLayout(jp7Layout);
        jp7Layout.setHorizontalGroup(
            jp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp7Layout.createSequentialGroup()
                .addGroup(jp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp7Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(jp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                        .addGap(47, 47, 47)
                        .addGroup(jp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfIDTab7)
                            .addComponent(tfNameTab7)
                            .addComponent(tfAddressTab7)
                            .addGroup(jp7Layout.createSequentialGroup()
                                .addComponent(cboxNamTab7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                                .addComponent(cboxNuTab7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))))
                    .addGroup(jp7Layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(319, 319, 319))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lableExit))
        );
        jp7Layout.setVerticalGroup(
            jp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp7Layout.createSequentialGroup()
                .addComponent(lableExit)
                .addGap(29, 29, 29)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp7Layout.createSequentialGroup()
                        .addGroup(jp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfIDTab7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNameTab7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96))
                    .addGroup(jp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboxNamTab7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboxNuTab7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74)
                .addGroup(jp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAddressTab7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jp2.setBackground(new java.awt.Color(242, 243, 244));

        tableTab2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tableTab2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã môn", "Tên môn", "Số tín chỉ", "Giáo viên LT", "Phòng học", "Ngày học", "Ca học"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableTab2);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Danh sách các môn đã đăng kí");

        lableExit2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lableExit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_35px.png"))); // NOI18N
        lableExit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableExit2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300))
                    .addComponent(lableExit2, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                .addComponent(lableExit2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );

        jp0.setBackground(new java.awt.Color(242, 243, 244));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cập nhật thông tin");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Tên mới");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Giới tính mới");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Địa chỉ mới");

        tfNameTab0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNameTab0.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tfAddressTab0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfAddressTab0.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnUpdateTab0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdateTab0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_update_user_25px_2.png"))); // NOI18N
        btnUpdateTab0.setText("Cập nhật");
        btnUpdateTab0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTab0ActionPerformed(evt);
            }
        });

        btnChangePassTab0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnChangePassTab0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_password_32px.png"))); // NOI18N
        btnChangePassTab0.setText("Đổi mật khẩu");
        btnChangePassTab0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassTab0ActionPerformed(evt);
            }
        });

        cbTab0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbTab0.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nữ", "Nam" }));

        lableExit4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lableExit4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_35px.png"))); // NOI18N
        lableExit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableExit4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp0Layout = new javax.swing.GroupLayout(jp0);
        jp0.setLayout(jp0Layout);
        jp0Layout.setHorizontalGroup(
            jp0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp0Layout.createSequentialGroup()
                .addGroup(jp0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp0Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(jp0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp0Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(jp0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp0Layout.createSequentialGroup()
                        .addGroup(jp0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNameTab0, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTab0, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(244, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp0Layout.createSequentialGroup()
                        .addGroup(jp0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jp0Layout.createSequentialGroup()
                                .addComponent(btnUpdateTab0, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnChangePassTab0))
                            .addComponent(tfAddressTab0))
                        .addGap(244, 244, 244))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp0Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jp0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp0Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(383, 383, 383))
                    .addComponent(lableExit4, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jp0Layout.setVerticalGroup(
            jp0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp0Layout.createSequentialGroup()
                .addComponent(lableExit4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jp0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfNameTab0, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jp0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbTab0, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jp0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfAddressTab0, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jp0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateTab0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangePassTab0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(144, 144, 144))
        );

        jp3.setBackground(new java.awt.Color(242, 243, 244));

        tableTab3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tableTab3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã môn học", "Tên môn học", "Số tín chỉ", "Giáo viên LT", "Phòng học", "Ngày học", "Ca học", "Select"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableTab3);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Xóa học phần");

        btnTab3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTab3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_25px.png"))); // NOI18N
        btnTab3.setText("Xóa");
        btnTab3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTab3ActionPerformed(evt);
            }
        });

        lableExit3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lableExit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_35px.png"))); // NOI18N
        lableExit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableExit3MouseClicked(evt);
            }
        });

        lable1Tab3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lable1Tab3.setText("a");

        lable2Tab3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lable2Tab3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lable2Tab3.setText("b");

        javax.swing.GroupLayout jp3Layout = new javax.swing.GroupLayout(jp3);
        jp3.setLayout(jp3Layout);
        jp3Layout.setHorizontalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(382, 382, 382))
                    .addComponent(lableExit3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3Layout.createSequentialGroup()
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jp3Layout.createSequentialGroup()
                                .addComponent(lable1Tab3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)
                                .addComponent(lable2Tab3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))))
        );
        jp3Layout.setVerticalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3Layout.createSequentialGroup()
                .addComponent(lableExit3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTab3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable1Tab3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable2Tab3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        tab1.setBackground(new Color(204, 204, 255));
        tab2.setBackground(new Color(253, 254, 254));
        tab3.setBackground(new Color(253, 254, 254));
        tab4.setBackground(new Color(253, 254, 254));
        tab0.setBackground(new Color(253, 254, 254));
        tab7.setBackground(new Color(253, 254, 254));

        jp1.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp0.setVisible(false);
        jp7.setVisible(false);

        showTableTab1();
        if (c == null) {
            lable1Tab1.setText("Chưa có kì đăng kí học phần!");
        } else {
            lable1Tab1.setText("Thời gian đăng kí: " + c.getNgayBatDau() + " đến " + c.getNgayKetThuc());
        }
        lable2Tab1.setText("Hôm nay: " + today);
    }//GEN-LAST:event_tab1MouseClicked

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        tab2.setBackground(new Color(204, 204, 255));
        tab1.setBackground(new Color(253, 254, 254));
        tab3.setBackground(new Color(253, 254, 254));
        tab4.setBackground(new Color(253, 254, 254));
        tab0.setBackground(new Color(253, 254, 254));
        tab7.setBackground(new Color(253, 254, 254));

        jp2.setVisible(true);
        jp1.setVisible(false);
        jp3.setVisible(false);
        jp0.setVisible(false);
        jp7.setVisible(false);
        showTableTab2();
    }//GEN-LAST:event_tab2MouseClicked

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        tab3.setBackground(new Color(204, 204, 255));
        tab2.setBackground(new Color(253, 254, 254));
        tab1.setBackground(new Color(253, 254, 254));
        tab4.setBackground(new Color(253, 254, 254));
        tab0.setBackground(new Color(253, 254, 254));
        tab7.setBackground(new Color(253, 254, 254));

        jp3.setVisible(true);
        jp2.setVisible(false);
        jp1.setVisible(false);
        jp0.setVisible(false);
        jp7.setVisible(false);
        showTableTab3();

        if (c == null) {
            lable1Tab3.setText("Chưa có kì đăng kí học phần!");
        } else {
            lable1Tab3.setText("Thời gian đăng kí: " + c.getNgayBatDau() + " đến " + c.getNgayKetThuc());
        }
        lable2Tab3.setText("Hôm nay: " + today);
    }//GEN-LAST:event_tab3MouseClicked

    private void tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab4MouseClicked
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tab4MouseClicked

    private void btnTab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTab1ActionPerformed
        if (c != null) {
            String ngayBatDau = c.getNgayBatDau();
            String ngayKetThuc = c.getNgayKetThuc();
            String[] s1 = ngayBatDau.split("-");
            String[] s2 = ngayKetThuc.split("-");
            String[] Today = today.split("-");
            if (checkNgayLonHon(s1, Today) == 1) {
                JOptionPane.showMessageDialog(rootPane, "Chưa tới thời gian đăng kí!");
                return;
            }
            if (checkNgayLonHon(Today, s2) == 1) {
                JOptionPane.showMessageDialog(rootPane, "Đã qua thời gian đăng kí!");
                return;
            }
        }

        if (c == null) {
            JOptionPane.showMessageDialog(rootPane, "Chưa có kì đăng kí học phần!");
            return;
        }

        List<course> listCourse = new ArrayList<>();
        for (int i = 0; i < modelTab1.getRowCount(); i++) {
            if ((boolean) modelTab1.getValueAt(i, 8) == true) {
                String maMonHoc = (String) modelTab1.getValueAt(i, 0);
                course c = CourseDAO.layThongTinCourse(maMonHoc);
                listCourse.add(c);
            }
        }

        if (listCourse.size() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Chưa đăng kí học phần nào!");
            return;
        } else if (listCourse.size() > 8) {
            JOptionPane.showMessageDialog(rootPane, "Chỉ được đăng kí tối đa 8 môn!");
            return;
        }

        for (int i = 0; i < listCourse.size() - 1; i++) {
            for (int j = i + 1; j < listCourse.size(); j++) {
                course x = listCourse.get(i);
                course y = listCourse.get(j);
                if (x.getCaHoc() == y.getCaHoc() && x.getNgayHoc().equals(y.getNgayHoc())) {
                    JOptionPane.showMessageDialog(rootPane, "Lịch học đã bị trùng, xem lại!");
                    return;
                }
            }
        }

        student st = StudentDAO.layThongTinSinhVien(login.staticUsername);
        if (st == null) {
            JOptionPane.showMessageDialog(rootPane, "Đăng kí học phần thất bại!");
        }

        for (course c : listCourse) {
            if (checkSet(c, st.getCourse_student()) == false) {
                st.getCourse_student().add(c);
            }
        }
        System.out.println(st.getCourse_student().size());
        for (course c : st.getCourse_student()) {
            System.out.println(c.getTenMon());
        }

        if (StudentDAO.capNhatThongTinStudent(st) == true) {
            JOptionPane.showMessageDialog(rootPane, "Đăng kí học phần thành công!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Đăng kí học phần thất bại!");
        }
    }//GEN-LAST:event_btnTab1ActionPerformed

    private static boolean checkSet(course str, Set<course> set) {
        for (course s : set) {
            if (s.getMaMonHoc().equals(str.getMaMonHoc()) == true) {
                return true;
            }
        }
        return false;
    }

    private void btnTab3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTab3ActionPerformed
        if (c != null) {
            String ngayBatDau = c.getNgayBatDau();
            String ngayKetThuc = c.getNgayKetThuc();
            String[] s1 = ngayBatDau.split("-");
            String[] s2 = ngayKetThuc.split("-");
            String[] Today = today.split("-");
            if (checkNgayLonHon(s1, Today) == 1) {
                JOptionPane.showMessageDialog(rootPane, "Chưa tới thời gian hủy học phần!");
                return;
            }
            if (checkNgayLonHon(Today, s2) == 1) {
                JOptionPane.showMessageDialog(rootPane, "Đã qua thời gian hủy học phần!");
                return;
            }
        }

        if (c == null) {
            JOptionPane.showMessageDialog(rootPane, "Chưa có kì đăng kí học phần!");
            return;
        }

        List<course> listCourse = new ArrayList<>();
        for (int i = 0; i < modelTab3.getRowCount(); i++) {
            if ((boolean) modelTab3.getValueAt(i, 7) == true) {
                String maMonHoc = (String) modelTab3.getValueAt(i, 0);
                course c = CourseDAO.layThongTinCourse(maMonHoc);
                listCourse.add(c);
            }
        }

        if (listCourse.size() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Chưa xóa học phần nào!");
            return;
        }

        student st = StudentDAO.layThongTinSinhVien(login.staticUsername);
        if (st == null) {
            JOptionPane.showMessageDialog(rootPane, "Xóa học phần thất bại!");
            return;
        }
        boolean flag = false;
        List<course> list = new ArrayList<>(st.getCourse_student());
        for (int i = 0; i < listCourse.size(); i++) {
            for (int j = 0; j < list.size(); j++) {
                if (listCourse.get(i).getMaMonHoc().equals(list.get(j).getMaMonHoc())) {
                    list.remove(j);
                    j--;
                    flag = true;
                }
            }
        }
        st.setCourse_student(new HashSet<>(list));
        if (StudentDAO.capNhatThongTinStudent(st) == true) {
            JOptionPane.showMessageDialog(rootPane, "Xóa học phần thành công!");
            for (int i = 0; i < modelTab3.getRowCount(); i++) {
                if ((boolean) modelTab3.getValueAt(i, 7) == true) {
                    modelTab3.removeRow(i);
                    i--;
                }
            }
            return;
        }

        JOptionPane.showMessageDialog(rootPane, "Xóa học phần thất bại!");
    }//GEN-LAST:event_btnTab3ActionPerformed

    private void tab0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab0MouseClicked
        tab0.setBackground(new Color(204, 204, 255));
        tab2.setBackground(new Color(253, 254, 254));
        tab3.setBackground(new Color(253, 254, 254));
        tab4.setBackground(new Color(253, 254, 254));
        tab1.setBackground(new Color(253, 254, 254));
        tab7.setBackground(new Color(253, 254, 254));

        jp0.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp1.setVisible(false);
        jp7.setVisible(false);
    }//GEN-LAST:event_tab0MouseClicked

    private void btnUpdateTab0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTab0ActionPerformed
        String name = tfNameTab0.getText();
        String address = tfAddressTab0.getText();
        int gioiTinh = cbTab0.getSelectedIndex();

        if (name.equals("") || address.equals("") || (gioiTinh != 0 && gioiTinh != 1)) {
            JOptionPane.showMessageDialog(rootPane, "Thông tin không được để trống!");
            return;
        }

        student st = StudentDAO.layThongTinSinhVien(login.staticUsername);
        if (st == null) {
            return;
        }
        st.setName(name);
        st.setAddress(address);
        st.setGioiTinh(gioiTinh);
        if (StudentDAO.capNhatThongTinStudent(st) == true) {
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin thành công!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin thất bại!");
        }
    }//GEN-LAST:event_btnUpdateTab0ActionPerformed

    private void btnChangePassTab0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassTab0ActionPerformed
        new changePass().setVisible(true);
    }//GEN-LAST:event_btnChangePassTab0ActionPerformed

    private void lableExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableExit1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lableExit1MouseClicked

    private void lableExit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableExit2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lableExit2MouseClicked

    private void lableExit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableExit3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lableExit3MouseClicked

    private void lableExit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableExit4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lableExit4MouseClicked

    private void tab7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab7MouseClicked
        tab7.setBackground(new Color(204, 204, 255));
        tab2.setBackground(new Color(253, 254, 254));
        tab3.setBackground(new Color(253, 254, 254));
        tab4.setBackground(new Color(253, 254, 254));
        tab1.setBackground(new Color(253, 254, 254));
        tab0.setBackground(new Color(253, 254, 254));

        jp7.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp1.setVisible(false);
        jp0.setVisible(false);

        student st = StudentDAO.layThongTinSinhVien(login.staticUsername);
        if (st == null) {
            return;
        }
        tfNameTab7.setText(st.getName());
        tfAddressTab7.setText(st.getAddress());
        tfIDTab7.setText(st.getId());
        if (st.getGioiTinh() == 1) {
            cboxNamTab7.setSelected(true);
            cboxNuTab7.setSelected(false);
        } else {
            cboxNuTab7.setSelected(true);
            cboxNamTab7.setSelected(false);
        }
    }//GEN-LAST:event_tab7MouseClicked

    private void lableExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lableExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinhVienGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePassTab0;
    private javax.swing.JButton btnTab1;
    private javax.swing.JButton btnTab3;
    private javax.swing.JButton btnUpdateTab0;
    private javax.swing.JComboBox<String> cbTab0;
    private javax.swing.JCheckBox cboxNamTab7;
    private javax.swing.JCheckBox cboxNuTab7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jp0;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp7;
    private javax.swing.JLabel lable;
    private javax.swing.JLabel lable1Tab1;
    private javax.swing.JLabel lable1Tab3;
    private javax.swing.JLabel lable2Tab1;
    private javax.swing.JLabel lable2Tab3;
    private javax.swing.JLabel lableExit;
    private javax.swing.JLabel lableExit1;
    private javax.swing.JLabel lableExit2;
    private javax.swing.JLabel lableExit3;
    private javax.swing.JLabel lableExit4;
    private javax.swing.JPanel tab0;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tab7;
    private javax.swing.JTable tableTab1;
    private javax.swing.JTable tableTab2;
    private javax.swing.JTable tableTab3;
    private javax.swing.JTextField tfAddressTab0;
    private javax.swing.JTextField tfAddressTab7;
    private javax.swing.JTextField tfIDTab7;
    private javax.swing.JTextField tfNameTab0;
    private javax.swing.JTextField tfNameTab7;
    // End of variables declaration//GEN-END:variables
}
