/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import  pojo.teacher;
import  dao.TeacherDAO;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class updateInfor extends javax.swing.JFrame {

    /**
     * Creates new form updateInfor
     */
    public updateInfor() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfEmailTab4 = new javax.swing.JTextField();
        tfPhoneNumberTab4 = new javax.swing.JTextField();
        lableTab4 = new javax.swing.JLabel();
        lableNameTab4 = new javax.swing.JLabel();
        tfAddressTab4 = new javax.swing.JTextField();
        lableEmailTab4 = new javax.swing.JLabel();
        btnPassTab4 = new javax.swing.JButton();
        btnUpdateTab4 = new javax.swing.JButton();
        lablePhoneNumberTab4 = new javax.swing.JLabel();
        lableAddressTab4 = new javax.swing.JLabel();
        tfNameTab4 = new javax.swing.JTextField();
        lableExit = new javax.swing.JLabel();

        setBackground(new java.awt.Color(229, 231, 233));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(229, 231, 233));

        tfEmailTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfEmailTab4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tfPhoneNumberTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfPhoneNumberTab4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lableTab4.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lableTab4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableTab4.setText("CẬP NHẬT THÔNG TIN");

        lableNameTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableNameTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableNameTab4.setText("Họ và tên");

        tfAddressTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfAddressTab4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lableEmailTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableEmailTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableEmailTab4.setText("Email");

        btnPassTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPassTab4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_password_32px.png"))); // NOI18N
        btnPassTab4.setText("Đổi mật khẩu");
        btnPassTab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassTab4ActionPerformed(evt);
            }
        });

        btnUpdateTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdateTab4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_update_user_25px_2.png"))); // NOI18N
        btnUpdateTab4.setText("Update");
        btnUpdateTab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTab4ActionPerformed(evt);
            }
        });

        lablePhoneNumberTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lablePhoneNumberTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lablePhoneNumberTab4.setText("Số điện thoại");

        lableAddressTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lableAddressTab4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lableAddressTab4.setText("Địa chỉ");

        tfNameTab4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNameTab4.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lableExit.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lableExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_35px.png"))); // NOI18N
        lableExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(lableTab4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lableNameTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(tfNameTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lableEmailTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(tfEmailTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lablePhoneNumberTab4)
                        .addGap(49, 49, 49)
                        .addComponent(tfPhoneNumberTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lableAddressTab4)
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUpdateTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPassTab4))
                            .addComponent(tfAddressTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lableExit))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lableExit)
                .addGap(31, 31, 31)
                .addComponent(lableTab4)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lableNameTab4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tfNameTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lableEmailTab4))
                    .addComponent(tfEmailTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lablePhoneNumberTab4))
                    .addComponent(tfPhoneNumberTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lableAddressTab4))
                    .addComponent(tfAddressTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPassTab4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPassTab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassTab4ActionPerformed
        new changePass().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPassTab4ActionPerformed

    private void btnUpdateTab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTab4ActionPerformed
        String name = tfNameTab4.getText();
        String email = tfEmailTab4.getText();
        String address = tfAddressTab4.getText();
        String phoneNumber = tfPhoneNumberTab4.getText();
        if (email.equals("") || name.equals("") || address.equals("") || phoneNumber.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Bạn phải nhập đầy đủ thông tin!");
            return;
        }

        teacher t = new teacher(login.staticUsername, name, email, address, phoneNumber);

        if (TeacherDAO.capNhatThongTinTeacher(t)) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin thành công!");
        } else {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin thất bại!");
        }
        this.dispose();
    }//GEN-LAST:event_btnUpdateTab4ActionPerformed

    private void lableExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_lableExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateInfor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPassTab4;
    private javax.swing.JButton btnUpdateTab4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lableAddressTab4;
    private javax.swing.JLabel lableEmailTab4;
    private javax.swing.JLabel lableExit;
    private javax.swing.JLabel lableNameTab4;
    private javax.swing.JLabel lablePhoneNumberTab4;
    private javax.swing.JLabel lableTab4;
    private javax.swing.JTextField tfAddressTab4;
    private javax.swing.JTextField tfEmailTab4;
    private javax.swing.JTextField tfNameTab4;
    private javax.swing.JTextField tfPhoneNumberTab4;
    // End of variables declaration//GEN-END:variables
}
